"use client";

import Link from "next/link";
import { ArrowLeft,ArrowRight,BookOpen,Clock3,Dices,Heart,Pause,Play,RotateCcw,Search,Shuffle } from "lucide-react";
import { useCallback,useEffect,useMemo,useState } from "react";
import { topicPracticeCategories,topicPracticeTopics } from "@/data/topic-practice/2026-09-23-topic-practice-data";
import type { TopicPractice } from "@/data/topic-practice/2026-09-23-topic-practice-types";

type Step="warmup"|"questions"|"vocabulary"|"expressions"|"roleplay"|"challenge";
const FAVORITES_KEY="language101-topic-practice-favorites";
const RECENT_KEY="language101-topic-practice-recent";
const steps:{id:Step;en:string;ko:string}[]=[{id:"warmup",en:"Warm Up",ko:"워밍업"},{id:"questions",en:"Questions",ko:"질문"},{id:"vocabulary",en:"Vocabulary",ko:"단어"},{id:"expressions",en:"Expressions",ko:"표현"},{id:"roleplay",en:"Role Play",ko:"롤플레이"},{id:"challenge",en:"Challenge",ko:"챌린지"}];
function readList(key:string){if(typeof window==="undefined")return[];try{const value=JSON.parse(localStorage.getItem(key)??"[]");return Array.isArray(value)?value.filter(item=>typeof item==="string"):[]}catch{return[]}}
function saveList(key:string,value:string[]){localStorage.setItem(key,JSON.stringify(value));window.dispatchEvent(new CustomEvent("language101-study-change"))}
function localDate(date=new Date()){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,"0"),d=String(date.getDate()).padStart(2,"0");return`${y}-${m}-${d}`}
function hash(value:string){let result=2166136261;for(const char of value){result^=char.charCodeAt(0);result=Math.imul(result,16777619)}return result>>>0}
export function getTodayTopic(date:string){return topicPracticeTopics[hash(`${date}:topic-practice`)%topicPracticeTopics.length]}

export function TopicPractice(){
 const [topic,setTopic]=useState<TopicPractice|null>(null),[step,setStep]=useState<Step>("warmup"),[search,setSearch]=useState(""),[category,setCategory]=useState<string>("All"),[favoriteOnly,setFavoriteOnly]=useState(false),[favorites,setFavorites]=useState<string[]>([]),[recent,setRecent]=useState<string[]>([]),[cardIndex,setCardIndex]=useState(0),[revealed,setRevealed]=useState(false),[roleIndex,setRoleIndex]=useState(0),[roleTimer,setRoleTimer]=useState(180),[remaining,setRemaining]=useState(180),[running,setRunning]=useState(false),[challengeIndex,setChallengeIndex]=useState(0);
 useEffect(()=>{queueMicrotask(()=>{setFavorites(readList(FAVORITES_KEY));setRecent(readList(RECENT_KEY))})},[]);
 useEffect(()=>{if(!running||remaining<=0)return;const timer=window.setInterval(()=>setRemaining(value=>{if(value<=1){setRunning(false);return 0}return value-1}),1000);return()=>window.clearInterval(timer)},[running,remaining]);
 const today=useMemo(()=>getTodayTopic(localDate()),[]);
 const filtered=useMemo(()=>topicPracticeTopics.filter(item=>{
  const aliases=item.category==="Dating & Relationships"?"date dating relationship love romance":"";
  const searchable=`${item.title} ${item.koreanTitle} ${item.category} ${aliases}`.toLowerCase();
  return (category==="All"||item.category===category)&&(!favoriteOnly||favorites.includes(item.id))&&searchable.includes(search.trim().toLowerCase());
 }),[category,favoriteOnly,favorites,search]);
 const openTopic=useCallback((next:TopicPractice)=>{setTopic(next);setStep("warmup");setCardIndex(0);setRevealed(false);setRoleIndex(0);setRunning(false);const updated=[next.id,...recent.filter(id=>id!==next.id)].slice(0,10);setRecent(updated);saveList(RECENT_KEY,updated)},[recent]);
 function toggleFavorite(id:string){const next=favorites.includes(id)?favorites.filter(item=>item!==id):[...favorites,id];setFavorites(next);saveList(FAVORITES_KEY,next)}
 function randomTopic(){const blocked=new Set(recent.slice(0,10));let pool=topicPracticeTopics.filter(item=>!blocked.has(item.id));if(!pool.length)pool=topicPracticeTopics;openTopic(pool[Math.floor(Math.random()*pool.length)])}
 function switchStep(next:Step){setStep(next);setCardIndex(0);setRevealed(false);setRunning(false);setRemaining(next==="challenge"?topic?.challenges[challengeIndex].seconds??30:roleTimer)}
 function move(delta:number,length:number){setCardIndex(value=>(value+delta+length)%length);setRevealed(false)}
 function shuffle(length:number){let next=Math.floor(Math.random()*length);if(length>1&&next===cardIndex)next=(next+1)%length;setCardIndex(next);setRevealed(false)}
 function setTimer(seconds:number){setRoleTimer(seconds);setRemaining(seconds);setRunning(false)}
 const timerText=remaining===0?"00:00":`${String(Math.floor(remaining/60)).padStart(2,"0")}:${String(remaining%60).padStart(2,"0")}`;

 if(!topic)return <main className="topic-practice"><header className="topic-practice-header"><Link href="/activities"><ArrowLeft/>Activities</Link><b>TOPIC PRACTICE<small>주제별 영어회화</small></b></header><section className="topic-practice-shell">
  <div className="topic-practice-hero"><BookOpen/><div><h1>Choose a topic and start talking!</h1><p>주제를 선택하고 영어로 대화를 시작해보세요.</p></div><button onClick={randomTopic}><Dices/>RANDOM TOPIC<small>랜덤 주제</small></button></div>
  <article className="topic-today"><span>TODAY&apos;S TOPIC<small>오늘의 주제</small></span><b>{today.emoji} {today.title}<small>{today.koreanTitle}</small></b><button onClick={()=>openTopic(today)}>Start<ArrowRight/></button></article>
  <div className="topic-filters"><label><Search/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search topics..."/></label><select aria-label="Category" value={category} onChange={event=>setCategory(event.target.value)}><option>All</option>{topicPracticeCategories.map(item=><option key={item}>{item}</option>)}</select><button aria-pressed={favoriteOnly} onClick={()=>setFavoriteOnly(value=>!value)}><Heart fill={favoriteOnly?"currentColor":"none"}/>Favorites</button></div>
  <p className="topic-results">{filtered.length} topics</p><section className="topic-grid">{filtered.map(item=><article key={item.id}><button className="topic-open" onClick={()=>openTopic(item)}><span>{item.emoji}</span><b>{item.title}<small>{item.koreanTitle}</small></b><em>{item.category}</em><ArrowRight/></button><button className={favorites.includes(item.id)?"is-favorite":""} aria-label={`Favorite ${item.title}`} onClick={()=>toggleFavorite(item.id)}><Heart fill={favorites.includes(item.id)?"currentColor":"none"}/></button></article>)}</section>{!filtered.length&&<p className="topic-empty">No matching topics.<small>조건에 맞는 주제가 없습니다.</small></p>}
 </section></main>;

 const questions=step==="warmup"?topic.warmupQuestions:topic.conversationQuestions,currentQuestion=questions[cardIndex%questions.length],vocab=topic.vocabulary[cardIndex%topic.vocabulary.length],expression=topic.expressions[cardIndex%topic.expressions.length],role=topic.rolePlays[roleIndex],challenge=topic.challenges[challengeIndex];
 return <main className="topic-practice topic-session"><header className="topic-practice-header"><button onClick={()=>setTopic(null)}><ArrowLeft/>Topics</button><b>{topic.emoji} {topic.title}<small>{topic.koreanTitle}</small></b><button className={favorites.includes(topic.id)?"is-favorite":""} aria-label="Favorite topic" onClick={()=>toggleFavorite(topic.id)}><Heart fill={favorites.includes(topic.id)?"currentColor":"none"}/></button></header><section className="topic-practice-shell">
  <nav className="topic-steps" aria-label="Practice steps">{steps.map((item,index)=><button className={step===item.id?"is-active":""} onClick={()=>switchStep(item.id)} key={item.id}><span>{index+1}</span>{item.en}<small>{item.ko}</small></button>)}</nav>
  {(step==="warmup"||step==="questions")&&<article className="topic-question-card"><span>{step==="warmup"?"WARM-UP":"QUESTION"} {cardIndex+1} / {questions.length}</span><h1>{currentQuestion.question}</h1><p>{currentQuestion.korean}</p><div><b>Follow-up</b>{currentQuestion.followUps.map(item=><p key={item}>{item}</p>)}</div><CardNav onPrevious={()=>move(-1,questions.length)} onShuffle={()=>shuffle(questions.length)} onNext={()=>move(1,questions.length)}/></article>}
  {step==="vocabulary"&&<article className={`topic-flash-card ${revealed?"is-revealed":""}`}><span>VOCABULARY {cardIndex+1} / {topic.vocabulary.length}</span><button onClick={()=>setRevealed(value=>!value)}><h1>{vocab.word.toUpperCase()}</h1>{revealed?<><h2>{vocab.korean}</h2><p>“{vocab.example}”</p></>:<p>Tap to see meaning<small>눌러서 뜻 보기</small></p>}</button><CardNav onPrevious={()=>move(-1,topic.vocabulary.length)} onShuffle={()=>shuffle(topic.vocabulary.length)} onNext={()=>move(1,topic.vocabulary.length)}/></article>}
  {step==="expressions"&&<article className="topic-expression-card"><span>USEFUL EXPRESSION {cardIndex+1} / {topic.expressions.length}</span><h1>{expression.expression}</h1><h2>{expression.korean}</h2><div><b>Example</b><p>“{expression.example}”</p></div><div><b>Practice</b><p>{expression.practice}</p></div><CardNav onPrevious={()=>move(-1,topic.expressions.length)} onShuffle={()=>shuffle(topic.expressions.length)} onNext={()=>move(1,topic.expressions.length)}/></article>}
  {step==="roleplay"&&<article className="topic-roleplay"><header><span>ROLE PLAY {roleIndex+1} / {topic.rolePlays.length}</span><h1>{role.title}</h1><p>{role.koreanTitle}</p></header><section><b>SITUATION<small>상황</small></b><p>{role.situation}</p><small>{role.koreanSituation}</small></section><div className="topic-roles"><article><b>ROLE A</b><p>{role.roleA}</p></article><article><b>ROLE B</b><p>{role.roleB}</p></article></div><aside><b>YOUR MISSION</b><p>{role.mission}</p></aside><ul>{role.usefulExpressions.map(item=><li key={item}>{item}</li>)}</ul><div className="topic-timer"><strong role="timer">{roleTimer===0?"NO TIMER":timerText}</strong><div>{[120,180,300,0].map(value=><button className={roleTimer===value?"is-active":""} key={value} onClick={()=>setTimer(value)}>{value?`${value/60} min`:"No Timer"}</button>)}</div>{roleTimer>0&&<button onClick={()=>setRunning(value=>!value)}>{running?<Pause/>:<Play/>}{running?"Pause":"START ROLE PLAY"}</button>}</div><CardNav onPrevious={()=>setRoleIndex(value=>(value+topic.rolePlays.length-1)%topic.rolePlays.length)} onShuffle={()=>setRoleIndex((roleIndex+1+Math.floor(Math.random()*(topic.rolePlays.length-1)))%topic.rolePlays.length)} onNext={()=>setRoleIndex(value=>(value+1)%topic.rolePlays.length)}/></article>}
  {step==="challenge"&&<article className="topic-challenge"><Clock3/><span>{challenge.title}</span><h1>{challenge.instruction}</h1><p>{challenge.korean}</p>{challenge.words&&<div>{challenge.words.map(word=><b key={word}>{word}</b>)}</div>}<strong role="timer">{timerText}</strong><div className="challenge-actions"><button onClick={()=>{setRemaining(challenge.seconds);setRunning(true)}}><Play/>START</button><button onClick={()=>{setRunning(false);setRemaining(challenge.seconds)}}><RotateCcw/>Reset</button></div><CardNav onPrevious={()=>{const next=(challengeIndex+topic.challenges.length-1)%topic.challenges.length;setChallengeIndex(next);setRemaining(topic.challenges[next].seconds)}} onShuffle={()=>{const next=(challengeIndex+1)%topic.challenges.length;setChallengeIndex(next);setRemaining(topic.challenges[next].seconds)}} onNext={()=>{const next=(challengeIndex+1)%topic.challenges.length;setChallengeIndex(next);setRemaining(topic.challenges[next].seconds)}}/></article>}
 </section></main>;
}

function CardNav({onPrevious,onShuffle,onNext}:{onPrevious:()=>void;onShuffle:()=>void;onNext:()=>void}){return <nav className="topic-card-nav"><button onClick={onPrevious}><ArrowLeft/>Previous</button><button onClick={onShuffle}><Shuffle/>Shuffle</button><button onClick={onNext}>Next<ArrowRight/></button></nav>}
