"use client";

import Link from "next/link";
import { ArrowLeft,ArrowRight,Eye,Heart,Maximize2,Minimize2,Search,Shuffle,Star } from "lucide-react";
import { useEffect,useMemo,useState } from "react";
import { usefulExpressionCategories,usefulExpressionPracticeItems,type UsefulExpressionDifficulty } from "@/data/2026-07-17-useful-expression-practice";
import { readUsefulExpressionFavorites,readUsefulExpressionRecent,rememberUsefulExpression,toggleUsefulExpressionFavorite,updateUsefulExpressionProgress } from "@/lib/2026-07-17-useful-expression-storage";
import { useLanguage } from "@/hooks/use-language";

const labels={en:{title:"Useful Expressions",guess:"What do you think this expression means?",reveal:"Show Answer",meaning:"Korean Meaning",example:"Example",translation:"Example Translation",questions:"Practice Questions",hint:"Answer Hint",previous:"Previous",next:"Next Expression",random:"Random",shuffle:"Shuffle",settings:"Search & Filters",table:"Table Mode",empty:"No expressions match your filters."},ko:{title:"실전 영어 표현",guess:"이 표현의 뜻은 무엇일까요?",reveal:"정답 보기",meaning:"한국어 뜻",example:"예문",translation:"예문 해석",questions:"대화 연습 질문",hint:"Answer Hint",previous:"이전",next:"다음 표현",random:"랜덤",shuffle:"섞기",settings:"검색 및 필터",table:"테이블 모드",empty:"필터에 맞는 표현이 없습니다."}};
type Order="frequency"|"shuffled";
const shuffleScore=(id:string,seed:number)=>[...id].reduce((hash,character)=>(hash*31+character.charCodeAt(0))%2147483647,seed||17);
export function UsefulExpressionPractice(){const{language}=useLanguage(),t=language==="ko"?labels.ko:labels.en;const[query,setQuery]=useState(""),[category,setCategory]=useState(""),[difficulty,setDifficulty]=useState(""),[favoritesOnly,setFavoritesOnly]=useState(false),[favorites,setFavorites]=useState<string[]>([]),[currentId,setCurrentId]=useState(usefulExpressionPracticeItems[0].id),[revealed,setRevealed]=useState(false),[questionsViewed,setQuestionsViewed]=useState(false),[tableMode,setTableMode]=useState(false),[order,setOrder]=useState<Order>("frequency"),[shuffleSeed,setShuffleSeed]=useState(0),[recent,setRecent]=useState<string[]>([]);
useEffect(()=>{const timer=setTimeout(()=>{setFavorites(readUsefulExpressionFavorites());setRecent(readUsefulExpressionRecent())},0);const sync=()=>setFavorites(readUsefulExpressionFavorites());window.addEventListener("storage",sync);window.addEventListener("language101-study-change",sync);return()=>{clearTimeout(timer);window.removeEventListener("storage",sync);window.removeEventListener("language101-study-change",sync)}},[]);
const filtered=useMemo(()=>{const normalized=query.trim().toLowerCase();const values=usefulExpressionPracticeItems.filter(item=>(!normalized||`${item.expression} ${item.koreanMeaning}`.toLowerCase().includes(normalized))&&(!category||item.category===category)&&(!difficulty||item.difficulty===difficulty)&&(!favoritesOnly||favorites.includes(item.id)));if(order==="frequency")return values;return [...values].sort((a,b)=>shuffleScore(a.id,shuffleSeed)-shuffleScore(b.id,shuffleSeed))},[query,category,difficulty,favoritesOnly,favorites,order,shuffleSeed]);
const current=filtered.find(item=>item.id===currentId)||filtered[0];const index=current?filtered.findIndex(item=>item.id===current.id):-1;
useEffect(()=>{if(!current)return;const timer=setTimeout(()=>{const next=rememberUsefulExpression(current.id);setRecent(next)},0);return()=>clearTimeout(timer)},[current]);
function select(nextId:string){setCurrentId(nextId);setRevealed(false);setQuestionsViewed(false)}function move(step:number){if(!filtered.length)return;select(filtered[(index+step+filtered.length)%filtered.length].id)}function random(){const pool=filtered.filter(item=>item.id!==current?.id&&!recent.includes(item.id));const values=pool.length?pool:filtered.filter(item=>item.id!==current?.id);if(values.length)select(values[Math.floor(Math.random()*values.length)].id)}function shuffle(){setOrder("shuffled");setShuffleSeed(Date.now()%997);if(filtered.length)random()}function reveal(){if(!current)return;setRevealed(true);updateUsefulExpressionProgress(current.id,current.expression,{answerRevealed:true})}function viewQuestions(open:boolean){if(!current||!open)return;setQuestionsViewed(true);updateUsefulExpressionProgress(current.id,current.expression,{questionsViewed:true})}function favorite(){if(!current)return;const active=toggleUsefulExpressionFavorite(current.id,current.expression);setFavorites(readUsefulExpressionFavorites());updateUsefulExpressionProgress(current.id,current.expression,{favorite:active})}
return <main className={`useful-practice ${tableMode?"is-table-mode":""}`}><header><Link href="/activities/useful-expressions"><ArrowLeft/>Back</Link><h1>{t.title}</h1><button onClick={()=>setTableMode(value=>!value)}>{tableMode?<Minimize2/>:<Maximize2/>}{t.table}</button></header>{!tableMode&&<section className="useful-filters"><label><Search/><input value={query}onChange={event=>setQuery(event.target.value)}placeholder="Search English or Korean"/></label><select value={category}onChange={event=>setCategory(event.target.value)}><option value="">All Categories</option>{usefulExpressionCategories.map(value=><option key={value}>{value}</option>)}</select><select value={difficulty}onChange={event=>setDifficulty(event.target.value as UsefulExpressionDifficulty|"")}><option value="">All Levels</option><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select><label><input type="checkbox"checked={favoritesOnly}onChange={event=>setFavoritesOnly(event.target.checked)}/>Favorites</label></section>}<section className="useful-practice-shell">{current?<><div className="useful-progress"><span>Expression</span><b>{index+1} / {filtered.length}</b><div><i style={{width:`${((index+1)/filtered.length)*100}%`}}/></div></div><article className="useful-expression-card"><div className="useful-card-meta"><span>{current.category}</span><span>{current.difficulty}</span><span>{current.frequency}</span><button aria-label="Favorite"className={favorites.includes(current.id)?"is-active":""}onClick={favorite}><Heart fill={favorites.includes(current.id)?"currentColor":"none"}/></button></div><small>Useful Expression</small><h2>{current.expression}</h2><div className="useful-guess"><span>🤔</span><p>{t.guess}</p></div>{!revealed?<button className="useful-reveal"onClick={reveal}><Eye/>{t.reveal}</button>:<div className="useful-answer"><section><small>{t.meaning}</small><strong>{current.koreanMeaning}</strong></section><section><small>{t.example}</small><p>{current.example}</p><small>{t.translation}</small><p>{current.exampleTranslation}</p></section><details onToggle={event=>viewQuestions((event.currentTarget as HTMLDetailsElement).open)} open={tableMode||questionsViewed}><summary>{t.questions}</summary>{current.questions.map((question,questionIndex)=><article key={question}><b>Question {questionIndex+1}</b><p>{question}</p><details><summary>{t.hint}</summary><p>{current.answerHint.en}</p><small>{current.answerHint.ko}</small></details></article>)}</details></div>}</article><div className="useful-navigation"><button onClick={()=>move(-1)}><ArrowLeft/>{t.previous}</button><button onClick={random}><Star/>{t.random}</button><button onClick={shuffle}><Shuffle/>{t.shuffle}</button><button className="is-primary"onClick={()=>move(1)}>{t.next}<ArrowRight/></button></div></>:<p className="study-empty">{t.empty}</p>}</section></main>}
