"use client";

import Link from "next/link";
import { ArrowDown,ArrowLeft,ArrowUp,Pencil,Plus,RotateCcw,Save,Trash2,X } from "lucide-react";
import { useState } from "react";
import { defaultTimeChallengePenalties,type TimeChallengePenalty } from "@/data/2026-07-25-time-challenge";
import { readTimeChallengePenalties,saveTimeChallengePenalties } from "@/lib/2026-07-25-time-challenge-storage";

export function TimeChallengeAdmin(){const [items,setItems]=useState<TimeChallengePenalty[]>(()=>typeof window==="undefined"?defaultTimeChallengePenalties:readTimeChallengePenalties());const [draft,setDraft]=useState("");const [editing,setEditing]=useState<string|null>(null);const [message,setMessage]=useState("");function commit(next:TimeChallengePenalty[]){setItems(next);saveTimeChallengePenalties(next);setMessage("저장되었습니다.")}function add(){const text=draft.trim();if(!text)return;commit([...items,{id:`penalty-${Date.now()}`,text}]);setDraft("")}function update(id:string,text:string){setItems(values=>values.map(item=>item.id===id?{...item,text}:item))}function finishEdit(){commit(items.filter(item=>item.text.trim()).map(item=>({...item,text:item.text.trim()})));setEditing(null)}function remove(id:string){commit(items.filter(item=>item.id!==id))}function move(index:number,direction:number){const target=index+direction;if(target<0||target>=items.length)return;const next=[...items];[next[index],next[target]]=[next[target],next[index]];commit(next)}function restore(){commit(defaultTimeChallengePenalties);setEditing(null)}return <main className="time-admin-page"><section className="time-admin-shell"><header><Link href="/activities/time-challenge/practice"><ArrowLeft/>Time Challenge</Link><span className="eyebrow">ADMIN · ACTIVITIES</span><h1>Penalty List</h1><p>벌칙을 추가·수정·삭제하고 표시 순서를 변경할 수 있습니다. 변경 내용은 이 브라우저에 저장됩니다.</p></header><div className="time-admin-create"><input value={draft} onChange={event=>setDraft(event.target.value)} onKeyDown={event=>{if(event.key==="Enter")add()}} placeholder="새 벌칙을 입력하세요"/><button onClick={add}><Plus/>Create</button></div><ol className="time-admin-list">{items.map((item,index)=><li key={item.id}><span>{index+1}</span>{editing===item.id?<input autoFocus value={item.text} onChange={event=>update(item.id,event.target.value)} onKeyDown={event=>{if(event.key==="Enter")finishEdit();if(event.key==="Escape")setEditing(null)}}/>:<b>{item.text}</b>}<div><button aria-label="위로 이동" disabled={index===0} onClick={()=>move(index,-1)}><ArrowUp/></button><button aria-label="아래로 이동" disabled={index===items.length-1} onClick={()=>move(index,1)}><ArrowDown/></button>{editing===item.id?<button onClick={finishEdit}><Save/>Save</button>:<button onClick={()=>setEditing(item.id)}><Pencil/>Edit</button>}<button onClick={()=>remove(item.id)}><Trash2/>Delete</button></div></li>)}</ol>{!items.length&&<p className="time-admin-empty">벌칙이 없습니다. 새 벌칙을 추가해 주세요.</p>}<footer><button onClick={restore}><RotateCcw/>기본 벌칙 복원</button><Link href="/activities/time-challenge/practice"><X/>관리 종료</Link></footer>{message&&<p role="status">{message}</p>}</section></main>}
