"use client";

import Link from "next/link";
import { ArrowDown,ArrowLeft,ArrowRight,ArrowUp,Clock3,GripVertical,Heart,Maximize2,Save,Settings,Shuffle,Users,X } from "lucide-react";
import { useCallback,useEffect,useMemo,useRef,useState } from "react";
import { RANK_IT_CATEGORIES,rankItTopics,type RankItCategory,type RankItDifficulty,type RankItLanguage,type RankItTopic } from "@/data/rank-it-topics";
import { calculateRankItStats,readRankItDraft,readRankItFavorites,saveRankItDraft,saveRankItPractice,toggleRankItFavorite,type RankItSavedRanking } from "@/lib/2026-07-18-rank-it-storage";
import { useLanguage } from "@/hooks/use-language";

type Mode="quick"|"group";type TimerChoice=0|30|60|90|120;
const ui={
 en:{back:"Rank It",settings:"Settings",table:"Table Mode",exitTable:"Exit Table Mode",topic:"Topic",of:"of",rank:"Rank these from best to worst.",quick:"Quick Rank",group:"Group Reveal",category:"Category",difficulty:"Difficulty",all:"All",allLevels:"All Levels",favoriteOnly:"Favorite Topics Only",fun:"Fun Challenge",timer:"Timer",off:"Off",players:"Players",player:"Player",saveRanking:"Save Ranking",nextPlayer:"Next Player",reveal:"Reveal Rankings",ready:"Everyone is ready. Reveal the rankings!",explain:"Explain Your Ranking",follow:"Show Follow-up Questions",hideFollow:"Hide Follow-up Questions",phrases:"Useful Phrases",needHelp:"Need Help?",defend:"Defend Your Ranking",challenge:"Challenge Another Player",previous:"Previous",random:"Random",next:"Next Topic",newTopic:"New Topic",save:"Save to My Study",saved:"Saved to My Study",memo:"Session memo",timesUp:"Time’s up! Finish your explanation.",popular:"Most popular #1",divisive:"Most divided opinion",average:"Group average ranking",similar:"Most similar",different:"Most different",noFavorites:"No Rank It favorites yet.",moveUp:"Move up",moveDown:"Move down",drag:"Drag to reorder",rankings:"Rankings",comparison:"Group Comparison"},
 ko:{back:"순위를 정해보세요",settings:"설정",table:"테이블 모드",exitTable:"테이블 모드 종료",topic:"주제",of:"/",rank:"가장 좋은 것부터 가장 낮은 것까지 순위를 정해보세요.",quick:"빠른 순위",group:"그룹 공개",category:"카테고리",difficulty:"난이도",all:"전체",allLevels:"전체 레벨",favoriteOnly:"즐겨찾기 주제만",fun:"재미 챌린지",timer:"타이머",off:"끄기",players:"참가자",player:"참가자",saveRanking:"순위 저장",nextPlayer:"다음 참가자",reveal:"순위 공개",ready:"모두 준비됐습니다. 순위를 공개하세요!",explain:"순위 설명하기",follow:"후속 질문 보기",hideFollow:"후속 질문 숨기기",phrases:"유용한 표현",needHelp:"도움이 필요하신가요?",defend:"내 순위 지키기",challenge:"다른 참가자 설득하기",previous:"이전",random:"랜덤",next:"다음 주제",newTopic:"새 주제",save:"My Study에 저장",saved:"My Study에 저장했어요",memo:"세션 메모",timesUp:"시간이 끝났어요! 설명을 마무리하세요.",popular:"가장 많이 선택된 1위",divisive:"의견이 가장 갈린 항목",average:"그룹 평균 순위",similar:"가장 비슷한 참가자",different:"가장 다른 참가자",noFavorites:"저장한 Rank It 즐겨찾기가 없습니다.",moveUp:"위로 이동",moveDown:"아래로 이동",drag:"드래그하여 순서 변경",rankings:"참가자 순위",comparison:"그룹 비교"},
 zh:{back:"排出顺序",settings:"设置",table:"桌面模式",exitTable:"退出桌面模式",topic:"主题",of:"/",rank:"请从最好到最差进行排序。",quick:"快速排名",group:"小组揭晓",category:"类别",difficulty:"难度",all:"全部",allLevels:"所有级别",favoriteOnly:"仅收藏主题",fun:"趣味挑战",timer:"计时器",off:"关闭",players:"玩家",player:"玩家",saveRanking:"保存排名",nextPlayer:"下一位玩家",reveal:"揭晓排名",ready:"所有人都准备好了。揭晓排名吧！",explain:"说明你的排名",follow:"显示后续问题",hideFollow:"隐藏后续问题",phrases:"实用表达",needHelp:"需要帮助？",defend:"为排名辩护",challenge:"挑战另一位玩家",previous:"上一个",random:"随机",next:"下一个主题",newTopic:"新主题",save:"保存到 My Study",saved:"已保存到 My Study",memo:"会话备注",timesUp:"时间到！请完成你的说明。",popular:"最多人选择的第一名",divisive:"分歧最大的选项",average:"小组平均排名",similar:"最相似的玩家",different:"差异最大的玩家",noFavorites:"还没有 Rank It 收藏。",moveUp:"上移",moveDown:"下移",drag:"拖动排序",rankings:"玩家排名",comparison:"小组比较"},
 ja:{back:"ランキングを決めよう",settings:"設定",table:"テーブルモード",exitTable:"テーブルモード終了",topic:"トピック",of:"/",rank:"最も良いものから順にランキングしてください。",quick:"クイックランク",group:"グループ公開",category:"カテゴリー",difficulty:"難易度",all:"すべて",allLevels:"全レベル",favoriteOnly:"お気に入りのみ",fun:"楽しいチャレンジ",timer:"タイマー",off:"オフ",players:"プレイヤー",player:"プレイヤー",saveRanking:"ランキング保存",nextPlayer:"次のプレイヤー",reveal:"ランキング公開",ready:"全員準備完了です。ランキングを公開しましょう！",explain:"ランキングを説明",follow:"追加質問を表示",hideFollow:"追加質問を隠す",phrases:"便利なフレーズ",needHelp:"ヘルプが必要？",defend:"ランキングを弁護",challenge:"他のプレイヤーに挑戦",previous:"前へ",random:"ランダム",next:"次のトピック",newTopic:"新しいトピック",save:"My Studyに保存",saved:"My Studyに保存しました",memo:"セッションメモ",timesUp:"時間切れです。説明を終えましょう。",popular:"最も多い1位",divisive:"意見が最も分かれた項目",average:"グループ平均順位",similar:"最も似たプレイヤー",different:"最も異なるプレイヤー",noFavorites:"Rank Itのお気に入りはまだありません。",moveUp:"上へ",moveDown:"下へ",drag:"ドラッグして並べ替え",rankings:"プレイヤー順位",comparison:"グループ比較"}
} as const;
const phrases={en:["I ranked ___ first because...","I put ___ at number five because...","In my experience...","I agree with your first choice, but...","I would rank ___ higher than ___.","The hardest choice for me was...","My ranking is based on...","I see your point, but I still think...","If I could change one thing, I would...","We seem to agree that..."],ko:["저는 ___을 1위로 정했어요. 왜냐하면…","저는 ___을 5위로 정했어요. 왜냐하면…","제 경험으로는…","당신의 1위 선택에는 동의하지만…","저는 ___을 ___보다 더 높은 순위에 둘 거예요.","가장 어려웠던 선택은…","제 순위는 ___을 기준으로 정했어요.","무슨 말인지는 알겠지만, 그래도 저는…","한 가지만 바꿀 수 있다면…","우리는 ___에 대해서는 의견이 같은 것 같아요."],zh:["我把___排在第一，因为……","我把___排在第五，因为……","根据我的经验……","我同意你的第一名，不过……","我会把___排在___之前。","最难选择的是……","我的排名依据是……","我明白你的观点，但我仍然认为……","如果可以改变一项，我会……","看来我们都同意……"],ja:["___を1位にしました。なぜなら…","___を5位にしました。なぜなら…","私の経験では…","あなたの1位には同意しますが…","___を___より上位にします。","最も難しかった選択は…","私のランキングは…を基準にしています。","言いたいことは分かりますが、それでも…","一つ変えられるなら…","私たちは…について同意しているようです。"]};

function shuffled<T>(items:T[]){const next=[...items];for(let i=next.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[next[i],next[j]]=[next[j],next[i]]}return next}
function initialTopic(){if(typeof window!=="undefined"){const requested=new URLSearchParams(location.search).get("topic");const found=rankItTopics.find(item=>item.id===requested);if(found)return found}return rankItTopics[0]}

export function RankItPractice(){
 const {language}=useLanguage();const lang=language as RankItLanguage;const c=ui[lang];
 const [topic,setTopic]=useState<RankItTopic>(initialTopic);const [order,setOrder]=useState(()=>initialTopic().options.map(item=>item.id));const [mode,setMode]=useState<Mode>("quick");const [category,setCategory]=useState<RankItCategory|"all">("all");const [difficulty,setDifficulty]=useState<RankItDifficulty|"all">("all");const [favoriteOnly,setFavoriteOnly]=useState(false);const [favorites,setFavorites]=useState<string[]>(()=>typeof window==="undefined"?[]:readRankItFavorites());const [seen,setSeen]=useState<string[]>([initialTopic().id]);const [history,setHistory]=useState<string[]>([initialTopic().id]);const [historyIndex,setHistoryIndex]=useState(0);const [players,setPlayers]=useState(["Player 1","Player 2"]);const [playerIndex,setPlayerIndex]=useState(0);const [rankings,setRankings]=useState<RankItSavedRanking[]>([]);const [revealed,setRevealed]=useState(false);const [showFollow,setShowFollow]=useState(false);const [showPhrases,setShowPhrases]=useState(false);const [funOn,setFunOn]=useState(true);const [table,setTable]=useState(false);const [settings,setSettings]=useState(false);const [timerChoice,setTimerChoice]=useState<TimerChoice>(0);const [remaining,setRemaining]=useState(0);const [running,setRunning]=useState(false);const [timeUp,setTimeUp]=useState(false);const [memo,setMemo]=useState("");const [message,setMessage]=useState("");const dragId=useRef<string|null>(null);
 const filtered=useMemo(()=>rankItTopics.filter(item=>(category==="all"||item.category===category)&&(difficulty==="all"||item.difficulty===difficulty)&&(!favoriteOnly||favorites.includes(item.id))),[category,difficulty,favoriteOnly,favorites]);
 const labels=useMemo(()=>Object.fromEntries(topic.options.map(item=>[item.id,item.label[lang]||item.label.en])),[topic,lang]);const stats=useMemo(()=>calculateRankItStats(rankings,labels),[rankings,labels]);const currentPlayer=players[playerIndex]?.trim()||`${c.player} ${playerIndex+1}`;
 useEffect(()=>{if(!running||remaining<=0)return;const timer=setInterval(()=>setRemaining(value=>{if(value<=1){setRunning(false);setTimeUp(true);return 0}return value-1}),1000);return()=>clearInterval(timer)},[running,remaining]);
 useEffect(()=>{const draft=readRankItDraft();if(!draft||Date.now()-Date.parse(draft.updatedAt)>86400000)return;const restored=rankItTopics.find(item=>item.id===draft.topicId);if(!restored)return;queueMicrotask(()=>{setTopic(restored);setOrder(draft.order);setMode(draft.mode);setPlayers(draft.players);setPlayerIndex(draft.playerIndex);setRankings(draft.rankings);setSeen(draft.seen);setHistory(draft.history);setHistoryIndex(draft.historyIndex);setFunOn(draft.funOn);setTimerChoice(draft.timer as TimerChoice);setCategory(draft.category);setDifficulty(draft.difficulty)})},[]);
 useEffect(()=>{if(typeof window==="undefined")return;const timer=setTimeout(()=>saveRankItDraft({topicId:topic.id,order,mode,players,playerIndex,rankings,seen,history,historyIndex,funOn,timer:timerChoice,category,difficulty,updatedAt:new Date().toISOString()}),150);return()=>clearTimeout(timer)},[topic.id,order,mode,players,playerIndex,rankings,seen,history,historyIndex,funOn,timerChoice,category,difficulty]);
 const openTopic=useCallback((next:RankItTopic,push=true)=>{setTopic(next);setOrder(shuffled(next.options.map(item=>item.id)));setRankings([]);setPlayerIndex(0);setRevealed(false);setShowFollow(false);setTimeUp(false);setRunning(false);setRemaining(timerChoice);setSeen(items=>items.includes(next.id)?items:[...items,next.id]);if(push)setHistory(items=>{const trimmed=items.slice(0,historyIndex+1);setHistoryIndex(trimmed.length);return[...trimmed,next.id]})},[historyIndex,timerChoice]);
 function chooseRandom(){const recent=new Set(seen.slice(-10));let pool=filtered.filter(item=>item.id!==topic.id&&!recent.has(item.id));if(!pool.length)pool=filtered.filter(item=>item.id!==topic.id);if(!pool.length)pool=filtered;const next=pool[Math.floor(Math.random()*pool.length)];if(next)openTopic(next)}
 function nextTopic(){const current=filtered.findIndex(item=>item.id===topic.id);openTopic(filtered[(Math.max(0,current)+1)%Math.max(1,filtered.length)]||rankItTopics[0])}
 function previous(){if(historyIndex<=0)return;const id=history[historyIndex-1];const previousTopic=rankItTopics.find(item=>item.id===id);if(previousTopic){setHistoryIndex(value=>value-1);openTopic(previousTopic,false)}}
 function move(id:string,direction:number){setOrder(items=>{const index=items.indexOf(id),target=index+direction;if(index<0||target<0||target>=items.length)return items;const next=[...items];[next[index],next[target]]=[next[target],next[index]];return next})}
 function moveBefore(id:string,targetId:string){if(id===targetId)return;setOrder(items=>{const next=items.filter(value=>value!==id),target=next.indexOf(targetId);next.splice(target<0?next.length:target,0,id);return next})}
 function saveCurrentRanking(){const ranking={player:currentPlayer,optionIds:[...order]};setRankings(items=>[...items.filter(item=>item.player!==currentPlayer),ranking]);if(playerIndex<players.length-1)setPlayerIndex(value=>value+1)}
 function toggleFavorite(){setFavorites(toggleRankItFavorite(topic.id))}
 function updateTimer(value:TimerChoice){setTimerChoice(value);setRemaining(value);setRunning(value>0);setTimeUp(false)}
 function save(){const all=mode==="group"?rankings.length?rankings:[{player:currentPlayer,optionIds:order}]:[{player:currentPlayer,optionIds:order}];const result=calculateRankItStats(all,labels),now=new Date();saveRankItPractice({id:`rank-it-${now.getTime()}`,activity:"rank-it",date:now.toLocaleDateString("en-CA"),topicId:topic.id,topicTitle:topic.title.en,ranking:order.map(id=>labels[id]),participantRankings:all,averageRanking:result.averageRanking,mostPopular:result.mostPopular,mostDivisive:result.mostDivisive,followUps:showFollow?topic.followUps.en:[],memo,favorite:favorites.includes(topic.id),category:topic.category,difficulty:topic.difficulty,createdAt:now.toISOString()});setMessage(c.saved)}
 function pointerMove(event:React.PointerEvent){if(!dragId.current)return;const target=document.elementFromPoint(event.clientX,event.clientY)?.closest<HTMLElement>("[data-rank-option]");if(target?.dataset.rankOption)moveBefore(dragId.current,target.dataset.rankOption)}
 const rankingCards=<ol className="rank-it-list" onPointerMove={pointerMove}>{order.map((id,index)=><li key={id} data-rank-option={id} draggable onDragStart={()=>{dragId.current=id}} onDragOver={event=>event.preventDefault()} onDrop={()=>{if(dragId.current)moveBefore(dragId.current,id);dragId.current=null}}><span className="rank-it-number" aria-label={`Rank ${index+1}`}>{index+1}</span><button className="rank-it-grip" aria-label={`${c.drag}: ${labels[id]}`} onPointerDown={event=>{dragId.current=id;event.currentTarget.setPointerCapture(event.pointerId)}} onPointerUp={()=>{dragId.current=null}}><GripVertical/></button><strong>{labels[id]}</strong><div><button onClick={()=>move(id,-1)} disabled={index===0} aria-label={`${c.moveUp}: ${labels[id]}`}><ArrowUp/></button><button onClick={()=>move(id,1)} disabled={index===order.length-1} aria-label={`${c.moveDown}: ${labels[id]}`}><ArrowDown/></button></div></li>)}</ol>;
 return <main className={`rank-it-practice${table?" is-table-mode":""}`}>
  {!table&&<header className="rank-it-header"><Link href="/activities/rank-it"><ArrowLeft/>{c.back}</Link><div><button onClick={()=>setSettings(value=>!value)}><Settings/>{c.settings}</button><button onClick={()=>setTable(true)}><Maximize2/>{c.table}</button></div></header>}
  <section className="rank-it-shell"><div className="rank-it-progress"><b>{c.topic} {rankItTopics.findIndex(item=>item.id===topic.id)+1} {c.of} 100</b><span>{topic.category} · {topic.difficulty}</span>{timerChoice>0&&<button onClick={()=>setRunning(value=>!value)}><Clock3/>{remaining}s</button>}</div>
  {!table&&<div className="rank-it-mode"><button className={mode==="quick"?"is-active":""} onClick={()=>setMode("quick")}>{c.quick}</button><button className={mode==="group"?"is-active":""} onClick={()=>setMode("group")}><Users/>{c.group}</button></div>}
  {settings&&!table&&<section className="rank-it-settings"><button className="settings-close" onClick={()=>setSettings(false)}><X/></button><label>{c.category}<select value={category} onChange={event=>{setCategory(event.target.value as RankItCategory|"all");setFavoriteOnly(false)}}><option value="all">{c.all}</option>{RANK_IT_CATEGORIES.map(value=><option value={value} key={value}>{value}</option>)}</select></label><label>{c.difficulty}<select value={difficulty} onChange={event=>setDifficulty(event.target.value as RankItDifficulty|"all")}><option value="all">{c.allLevels}</option><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label><label>{c.timer}<select value={timerChoice} onChange={event=>updateTimer(Number(event.target.value) as TimerChoice)}><option value="0">{c.off}</option>{[30,60,90,120].map(value=><option value={value} key={value}>{value<120?`${value} seconds`:"2 minutes"}</option>)}</select></label><label className="rank-it-toggle"><input type="checkbox" checked={favoriteOnly} onChange={event=>setFavoriteOnly(event.target.checked)}/>{c.favoriteOnly}</label><label className="rank-it-toggle"><input type="checkbox" checked={funOn} onChange={event=>setFunOn(event.target.checked)}/>{c.fun}</label>{mode==="group"&&<div className="rank-it-player-settings"><b>{c.players}: {players.length}</b>{players.map((name,index)=><input aria-label={`${c.player} ${index+1}`} key={index} value={name} onChange={event=>setPlayers(items=>items.map((item,i)=>i===index?event.target.value:item))}/>)}<div><button disabled={players.length<=2} onClick={()=>setPlayers(items=>items.slice(0,-1))}>−</button><button disabled={players.length>=8} onClick={()=>setPlayers(items=>[...items,`Player ${items.length+1}`])}>+</button></div></div>}<p>{filtered.length} / 100</p></section>}
  {!filtered.length?<div className="rank-it-empty"><p>{c.noFavorites}</p><button onClick={()=>setFavoriteOnly(false)}>{c.all}</button></div>:<><article className="rank-it-card"><div className="rank-it-card-head"><div><small>RANK IT</small><h1>{topic.title[lang]||topic.title.en}</h1><p>{topic.prompt[lang]||c.rank}</p></div><button className={favorites.includes(topic.id)?"is-active":""} onClick={toggleFavorite} aria-label="Favorite"><Heart fill={favorites.includes(topic.id)?"currentColor":"none"}/></button></div>{mode==="group"&&<h2>{currentPlayer}’s Ranking</h2>}{rankingCards}{timeUp&&<p className="rank-it-timeup" role="status">{c.timesUp}</p>}{mode==="group"&&<div className="rank-it-group-actions"><button onClick={saveCurrentRanking}><Save/>{c.saveRanking}</button>{playerIndex<players.length-1&&<button onClick={()=>setPlayerIndex(value=>Math.min(players.length-1,value+1))}>{c.nextPlayer}</button>}<button className="button button-primary" disabled={rankings.length<players.length} onClick={()=>setRevealed(true)}>{c.reveal}</button>{rankings.length>=players.length&&!revealed&&<p>{c.ready}</p>}</div>}</article>
  {(mode==="quick"||rankings.length>0)&&<section className="rank-it-conversation"><h2>{c.explain}</h2><div className="rank-it-speaking-prompts"><button>{c.defend}</button><p>Why did you rank {labels[order[0]]} higher than {labels[order[1]]}?</p><button>{c.challenge}</button><p>Convince another player to move one item into their top two.</p></div><button className="rank-it-disclosure" onClick={()=>setShowFollow(value=>!value)}>{showFollow?c.hideFollow:c.follow}</button>{showFollow&&<ol>{topic.followUps[lang].map(question=><li key={question}>{question}</li>)}</ol>}<button className="rank-it-disclosure" onClick={()=>setShowPhrases(value=>!value)}>{c.needHelp} · {c.phrases}</button>{showPhrases&&<ul className="rank-it-phrases">{phrases[lang].map(phrase=><li key={phrase}>{phrase}</li>)}</ul>}{funOn&&<aside className="rank-it-fun"><b>{c.fun}</b><p>{topic.funChallenge[lang]}</p></aside>}</section>}
  {revealed&&<section className="rank-it-results"><h2>{c.comparison}</h2><div className="rank-it-result-stats"><article><small>{c.popular}</small><b>{stats.mostPopular}</b></article><article><small>{c.divisive}</small><b>{stats.mostDivisive}</b></article><article><small>{c.similar}</small><b>{stats.mostSimilar}</b></article><article><small>{c.different}</small><b>{stats.mostDifferent}</b></article></div><h3>{c.average}</h3><ol>{stats.averageRanking.map(item=><li key={item.option}><b>{item.option}</b><span>{item.average.toFixed(1)}</span></li>)}</ol><h3>{c.rankings}</h3>{rankings.map(ranking=><article className="rank-it-player-result" key={ranking.player}><b>{ranking.player}</b><ol>{ranking.optionIds.map(id=><li key={id}>{labels[id]}</li>)}</ol></article>)}</section>}
  {!table&&<section className="rank-it-save"><textarea value={memo} onChange={event=>setMemo(event.target.value)} placeholder={c.memo}/><button onClick={save}><Save/>{c.save}</button>{message&&<p role="status">{message}</p>}</section>}
  <nav className="rank-it-navigation"><button aria-label={c.previous} onClick={previous} disabled={historyIndex<=0}>{c.previous}</button><button aria-label={c.random} onClick={chooseRandom}><Shuffle/>{c.random}</button><button className="button button-primary rank-it-next" aria-label={c.next} onClick={nextTopic}><span>{c.next}</span><ArrowRight aria-hidden="true"/></button></nav></>}
  {table&&<button className="rank-it-exit-table" onClick={()=>setTable(false)}><X/>{c.exitTable}</button>}</section>
 </main>
}
