"use client";
import Link from "next/link";
import { ArrowLeft, Check, ChevronDown, ChevronLeft, ChevronRight, Clock3, Dices, Heart, Maximize2, Settings, Shuffle, SkipForward, Star, Users, X } from "lucide-react";
import { useEffect,useMemo,useRef,useState } from "react";
import { FUNNY_CATEGORIES,funnyQuestions,type FunnyQuestion,type FunnyQuestionCategory,type FunnyQuestionDifficulty } from "@/data/2026-07-17-funny-questions";
import { incrementFunnyStat,readFunnyFavorites,readFunnyRatings,saveFunnyRating,saveFunnySession,toggleFunnyFavorite,type FunnyRating } from "@/lib/2026-07-17-funny-questions-storage";
import { useLanguage } from "@/hooks/use-language";

type Mode="random"|"number"|"category"; type TimerChoice=0|30|45|60|90;
const ui={
 en:{title:"Funny Questions",question:"FUNNY QUESTION",settings:"Settings",randomMode:"Random Question",numberMode:"Pick a Number",categoryMode:"Category Challenge",all:"All",next:"Next",previous:"Previous",random:"Random",skip:"Skip",follow:"Show Follow-up Questions",hideFollow:"Hide Follow-up Questions",help:"Need Help?",hideHelp:"Hide Answer Help",personal:"Personal",sensitive:"Sensitive",translation:"Show Translation",challenge:"3-Sentence Challenge",react:"React to the speaker before moving on.",fun:"Fun Challenge",group:"Group Play",table:"Table Mode",exitTable:"Exit Table Mode",finish:"Save Session",saved:"Saved to My Study",numberError:"Enter a number from 1 to 500.",uncomfortable:"You can pass any question that makes you uncomfortable.",great:"Great answer! Keep the conversation going.",timesUp:"Time’s up! Finish your sentence.",nextPlayer:"Next Player",everyone:"Everyone Answers",newQuestion:"New Question",favoriteOnly:"Favorite Questions Only",shuffle:"Shuffle Session",memo:"Session memo",save:"Save to My Study"},
 ko:{title:"재미있는 질문",question:"FUNNY QUESTION",settings:"설정",randomMode:"랜덤 질문",numberMode:"번호 선택",categoryMode:"카테고리 도전",all:"전체",next:"다음",previous:"이전",random:"랜덤",skip:"건너뛰기",follow:"후속 질문 보기",hideFollow:"후속 질문 숨기기",help:"답변 도움말",hideHelp:"답변 도움말 숨기기",personal:"개인 질문",sensitive:"민감 질문",translation:"번역 보기",challenge:"3문장 챌린지",react:"다음 사람으로 넘어가기 전에 답변자에게 영어로 반응해 보세요.",fun:"재미 챌린지",group:"그룹 플레이",table:"테이블 모드",exitTable:"테이블 모드 종료",finish:"세션 저장",saved:"My Study에 저장했어요",numberError:"1부터 500 사이의 숫자를 입력하세요.",uncomfortable:"불편한 질문은 언제든 건너뛸 수 있습니다.",great:"멋진 답변이에요! 대화를 계속 이어가 보세요.",timesUp:"시간이 끝났어요! 말하던 문장을 마무리하세요.",nextPlayer:"다음 참가자",everyone:"모두 답하기",newQuestion:"새 질문",favoriteOnly:"즐겨찾기만",shuffle:"셔플 세션",memo:"세션 메모",save:"My Study에 저장"}
};
const categoryKo:Record<FunnyQuestionCategory,string>={"Wild What-Ifs":"황당한 상상","Funny Daily Life":"웃긴 일상","Honest TMI":"솔직한 TMI","Food & Weird Tastes":"음식과 독특한 취향","Travel & Adventure":"여행과 모험","Love & Relationships":"연애와 인간관계","Work & Money":"일과 돈","Would You Rather":"기발한 선택","Personality":"성격과 습관","Childhood & Memories":"어린 시절과 추억","Pop Culture & Entertainment":"문화와 엔터테인먼트","Superpowers & Fantasy":"초능력과 판타지","Awkward Moments":"민망한 순간","Light Debates":"가벼운 논쟁","Future & Dreams":"미래와 꿈"};
const ratingOptions:[FunnyRating,string][]=[["very-funny","😂 Very Funny"],["fun","😄 Fun"],["easy","🙂 Easy Conversation"],["interesting","💭 Interesting"]];

export function FunnyQuestionsPractice(){
 const {language}=useLanguage();const l=language==="ko"?"ko":"en";const c=ui[l];
 const [mode,setMode]=useState<Mode>("random"),[category,setCategory]=useState<FunnyQuestionCategory|"all">("all"),[difficulty,setDifficulty]=useState<FunnyQuestionDifficulty|"all">("all"),[sensitive,setSensitive]=useState(false),[personal,setPersonal]=useState(true),[favoriteOnly,setFavoriteOnly]=useState(false),[funOn,setFunOn]=useState(true),[timerChoice,setTimerChoice]=useState<TimerChoice>(0),[groupOn,setGroupOn]=useState(false),[showTranslation,setShowTranslation]=useState(true),[settings,setSettings]=useState(false),[table,setTable]=useState(false);
 const [current,setCurrent]=useState<FunnyQuestion>(funnyQuestions[0]),[history,setHistory]=useState<string[]>([funnyQuestions[0].id]),[historyIndex,setHistoryIndex]=useState(0),[recent,setRecent]=useState<string[]>([funnyQuestions[0].id]),[seen,setSeen]=useState<string[]>([funnyQuestions[0].id]),[shuffleIds,setShuffleIds]=useState<string[]>([]),[shuffleIndex,setShuffleIndex]=useState(0);
 const [favorites,setFavorites]=useState<string[]>([]),[ratings,setRatings]=useState<Record<string,FunnyRating>>({}),[follow,setFollow]=useState(false),[help,setHelp]=useState(false),[checks,setChecks]=useState([false,false,false]),[reaction,setReaction]=useState(""),[number,setNumber]=useState(""),[error,setError]=useState(""),[players,setPlayers]=useState(["Player 1","Player 2"]),[playerIndex,setPlayerIndex]=useState(0),[everyone,setEveryone]=useState(false),[remaining,setRemaining]=useState(0),[timeUp,setTimeUp]=useState(false),[memo,setMemo]=useState(""),[message,setMessage]=useState("");
 const timerRef=useRef<ReturnType<typeof setInterval>|null>(null);
 useEffect(()=>{const load=setTimeout(()=>{setFavorites(readFunnyFavorites().map(item=>item.questionId));setRatings(readFunnyRatings());incrementFunnyStat(funnyQuestions[0].id,"viewed")},0);return()=>clearTimeout(load)},[]);
 useEffect(()=>{if(timerRef.current)clearInterval(timerRef.current);if(!timerChoice)return;timerRef.current=setInterval(()=>setRemaining(value=>{if(value<=1){if(timerRef.current)clearInterval(timerRef.current);setTimeUp(true);return 0}return value-1}),1000);return()=>{if(timerRef.current)clearInterval(timerRef.current)}},[current.id,timerChoice]);
 const filtered=useMemo(()=>funnyQuestions.filter(q=>(category==="all"||q.category===category)&&(difficulty==="all"||q.difficulty===difficulty)&&(sensitive||q.sensitivity!=="sensitive")&&(personal||q.sensitivity==="safe")&&(!favoriteOnly||favorites.includes(q.id))),[category,difficulty,sensitive,personal,favoriteOnly,favorites]);
 function showQuestion(next:FunnyQuestion,replaceHistory=false){setCurrent(next);setFollow(false);setHelp(false);setChecks([false,false,false]);setReaction("");setError("");setTimeUp(false);setRemaining(timerChoice);setRecent(items=>[...items.filter(id=>id!==next.id),next.id].slice(-20));setSeen(items=>items.includes(next.id)?items:[...items,next.id]);incrementFunnyStat(next.id,"viewed");if(!replaceHistory){setHistory(items=>[...items.slice(0,historyIndex+1),next.id]);setHistoryIndex(value=>value+1)}}
 function randomQuestion(skip=false){let pool=filtered.filter(q=>q.id!==current.id&&!recent.includes(q.id));if(!pool.length)pool=filtered.filter(q=>q.id!==current.id);if(!pool.length)pool=filtered;if(!pool.length){setError("No questions match these settings.");return}if(skip)incrementFunnyStat(current.id,"skipped");showQuestion(pool[Math.floor(Math.random()*pool.length)])}
 function goHistory(delta:number){const index=historyIndex+delta;if(index<0||index>=history.length)return;const found=funnyQuestions.find(q=>q.id===history[index]);if(found){setHistoryIndex(index);setCurrent(found);setFollow(false);setHelp(false);setChecks([false,false,false])}}
 function pickNumber(){const value=Number(number);if(!Number.isInteger(value)||value<1||value>500){setError(c.numberError);return}showQuestion(funnyQuestions[value-1])}
 function startShuffle(){const ids=[...filtered].sort(()=>Math.random()-.5).map(q=>q.id);setShuffleIds(ids);setShuffleIndex(0);const first=funnyQuestions.find(q=>q.id===ids[0]);if(first)showQuestion(first);}
 function nextShuffle(){if(!shuffleIds.length){startShuffle();return}const index=(shuffleIndex+1)%shuffleIds.length;setShuffleIndex(index);const next=funnyQuestions.find(q=>q.id===shuffleIds[index]);if(next)showQuestion(next)}
 function toggleFavorite(){const next=toggleFunnyFavorite(current);setFavorites(next.map(item=>item.questionId))}
 function rate(value:FunnyRating){setRatings(saveFunnyRating(current.id,value))}
 function addPlayer(){if(players.length<10)setPlayers(items=>[...items,`Player ${items.length+1}`])}
 function nextPlayer(){if(playerIndex===players.length-1&&everyone){setMessage("Everyone answered! Choose a new question.");setEveryone(false);return}setPlayerIndex(value=>(value+1)%players.length)}
 function save(){const now=new Date();saveFunnySession({id:`funny-session-${now.getTime()}`,activity:"funny-questions",date:now.toLocaleDateString("en-CA"),mode,participants:players,viewedCount:seen.length,answeredQuestionIds:seen,categories:[...new Set(seen.map(id=>funnyQuestions.find(q=>q.id===id)?.category).filter(Boolean))] as FunnyQuestionCategory[],favoriteQuestionIds:favorites,funniestQuestionId:Object.entries(ratings).find(([,value])=>value==="very-funny")?.[0],reactions:reaction?[reaction]:[],memo,createdAt:now.toISOString()});setMessage(c.saved)}
 const contentLanguage=language==="ko"?"ko":language==="zh"?"zh":language==="ja"?"ja":"en";
 return <main className={`funny-practice ${table?"is-table":""}`}>
  {!table&&<header className="funny-header"><Link href="/activities/funny-questions"><ArrowLeft/> {c.title}</Link><div><button onClick={()=>setSettings(true)}><Settings/> {c.settings}</button><button onClick={()=>setTable(true)}><Maximize2/> {c.table}</button></div></header>}
  <section className="funny-shell">
   {groupOn&&<div className="funny-turn"><Users/><b>{players[playerIndex]}’s Turn</b><span>{playerIndex+1}/{players.length}</span></div>}
   <article className="funny-question-card"><div className="funny-card-meta"><span>#{current.number}</span><span>{language==="ko"?categoryKo[current.category]:current.category}</span><span>{current.difficulty}</span>{current.sensitivity!=="safe"&&<span className={current.sensitivity}>{current.sensitivity==="personal"?c.personal:c.sensitive}</span>}<button aria-label="Favorite" className={favorites.includes(current.id)?"is-active":""} onClick={toggleFavorite}><Heart/></button></div><small>{c.question}</small><h1>{current.question.en}</h1>{showTranslation&&contentLanguage!=="en"&&<p>{current.question[contentLanguage]||current.question.en}</p>}<p className="funny-comfort">{c.uncomfortable}</p></article>
   {timerChoice>0&&<div className={`funny-timer ${timeUp?"is-up":""}`}><Clock3/><strong>{remaining}s</strong>{timeUp&&<span>{c.timesUp}</span>}</div>}
   <section className="funny-challenge"><h2>{c.challenge}</h2><ol><li>Give your answer.</li><li>Explain why.</li><li>Add an example or experience.</li></ol><div>{checks.map((checked,index)=><button className={checked?"is-active":""} key={index} onClick={()=>setChecks(items=>items.map((item,i)=>i===index?!item:item))}>{checked&&<Check/>} Sentence {index+1}</button>)}</div>{checks.every(Boolean)&&<b>{c.great}</b>}</section>
   {funOn&&<aside className="funny-fun"><Star/><div><b>{c.fun}</b><p>{current.funChallenge}</p></div></aside>}
   <div className="funny-disclosures"><button onClick={()=>setHelp(!help)}>{help?c.hideHelp:c.help}<ChevronDown/></button>{help&&<div className="funny-helper">{current.answerStarters.en.map((item,index)=><p key={item}><b>{item}</b>{contentLanguage!=="en"&&<span>{current.answerStarters[contentLanguage][index]||item}</span>}</p>)}</div>}<button onClick={()=>setFollow(!follow)}>{follow?c.hideFollow:c.follow}<ChevronDown/></button>{follow&&<ol className="funny-helper">{current.followUps.en.map((item,index)=><li key={item}><b>{item}</b>{contentLanguage!=="en"&&<span>{current.followUps[contentLanguage][index]||item}</span>}</li>)}</ol>}</div>
   <section className="funny-reactions"><h2>Reaction Challenge</h2><p>{c.react}</p><div>{current.reactionPrompts.map(item=><button className={reaction===item?"is-active":""} onClick={()=>setReaction(item)} key={item}>{item}</button>)}</div></section>
   <section className="funny-ratings">{ratingOptions.map(([value,label])=><button className={ratings[current.id]===value?"is-active":""} onClick={()=>rate(value)} key={value}>{label}</button>)}</section>
   {mode==="number"&&<div className="funny-number"><input inputMode="numeric" min="1" max="500" value={number} onChange={e=>setNumber(e.target.value)} placeholder="1–500"/><button onClick={pickNumber}>Go</button></div>}{error&&<p className="funny-error">{error}</p>}
   {groupOn?<div className="funny-actions group"><button onClick={()=>randomQuestion(true)}><SkipForward/> {c.skip}</button><button onClick={nextPlayer}><Users/> {c.nextPlayer}</button><button onClick={()=>randomQuestion()}><Dices/> {c.newQuestion}</button><button onClick={()=>{setEveryone(true);setPlayerIndex(0)}}>{c.everyone}</button></div>:<div className="funny-actions"><button disabled={historyIndex===0} onClick={()=>goHistory(-1)}><ChevronLeft/> {c.previous}</button><button onClick={()=>randomQuestion()}><Dices/> {c.random}</button><button onClick={()=>shuffleIds.length?nextShuffle():randomQuestion()}>{c.next} <ChevronRight/></button></div>}
   {!table&&<section className="funny-save"><textarea value={memo} onChange={e=>setMemo(e.target.value)} placeholder={c.memo}/><button onClick={save}>{c.save}</button>{message&&<p>{message}</p>}</section>}
  </section>
  {table&&<button className="funny-exit-table" onClick={()=>setTable(false)}><X/> {c.exitTable}</button>}
  {settings&&<div className="funny-settings-backdrop" onClick={()=>setSettings(false)}><section className="funny-settings" onClick={e=>e.stopPropagation()}><header><h2>{c.settings}</h2><button onClick={()=>setSettings(false)}><X/></button></header><label>Mode<select value={mode} onChange={e=>setMode(e.target.value as Mode)}><option value="random">{c.randomMode}</option><option value="number">{c.numberMode}</option><option value="category">{c.categoryMode}</option></select></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value as FunnyQuestionCategory|"all")}><option value="all">{c.all}</option>{FUNNY_CATEGORIES.map(item=><option key={item}>{item}</option>)}</select></label><label>Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value as FunnyQuestionDifficulty|"all")}><option value="all">{c.all}</option><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label><label>Timer<select value={timerChoice} onChange={e=>setTimerChoice(Number(e.target.value) as TimerChoice)}><option value="0">Off</option>{[30,45,60,90].map(value=><option value={value} key={value}>{value} seconds</option>)}</select></label>{[[c.sensitive,sensitive,setSensitive],[c.personal,personal,setPersonal],[c.fun,funOn,setFunOn],[c.group,groupOn,setGroupOn],[c.translation,showTranslation,setShowTranslation],[c.favoriteOnly,favoriteOnly,setFavoriteOnly]] .map(([label,value,setter])=><label className="funny-toggle" key={String(label)}><span>{String(label)}</span><input type="checkbox" checked={Boolean(value)} onChange={e=>(setter as (v:boolean)=>void)(e.target.checked)}/></label>)}{groupOn&&<div className="funny-players">{players.map((name,index)=><input key={index} value={name} onChange={e=>setPlayers(items=>items.map((item,i)=>i===index?e.target.value:item))}/>)}<button onClick={addPlayer} disabled={players.length>=10}>+ Player</button></div>}<button className="button button-secondary" onClick={startShuffle}><Shuffle/> {c.shuffle}</button><p>{filtered.length} / 500 questions</p></section></div>}
 </main>
}
