"use client";
import { useEffect,useMemo,useRef,useState } from "react";import { RotateCcw,Shuffle } from "lucide-react";import { useRouter } from "next/navigation";
import { randomEligibleActivities } from "@/data/activities";import { activityFilterOptions,defaultFilters,filterActivities,type ActivityFilters } from "@/lib/activity-utils";import { localizeActivity } from "@/lib/activity-localization";import { FILTER_STORAGE_KEY,RANDOM_HISTORY_KEY,RECENT_RANDOM_KEY } from "@/lib/navigation";import { nextRandomHistory,pickWheelItemIndex,selectWheelItems,splitWheelTitle,wheelFontSize } from "@/lib/random-wheel";import { getIndexAtPointer,getRotationForIndex,getSegmentCenterAngle,getSegmentPath } from "@/lib/wheel-geometry";import type { Activity } from "@/types/activity";import { useLanguage } from "@/hooks/use-language";
const colors=["#6c4cf1","#8b6cf6","#4f63d8","#a454d2","#5579c6","#7852b9","#397f8e","#b55d78"];
const readJson=<T,>(key:string,fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key)||"") as T}catch{return fallback}};
type SpinResult={activity:Activity;id:string;slug:string;title:string;index:number;rotation:number};
export function ActivityWheel(){const {language,t}=useLanguage();const router=useRouter();const wheelRef=useRef<HTMLDivElement|null>(null);const itemsRef=useRef<Activity[]>(randomEligibleActivities);const redirectRef=useRef<ReturnType<typeof setTimeout>|null>(null);const spinFallbackRef=useRef<ReturnType<typeof setTimeout>|null>(null);const completedRef=useRef(false);const [filters,setFilters]=useState<ActivityFilters>(defaultFilters);const [items,setItems]=useState<Activity[]>(()=>randomEligibleActivities);const [history,setHistory]=useState<string[]>([]);const [rotation,setRotation]=useState(0);const [spinning,setSpinning]=useState(false);const [selectedResult,setSelectedResult]=useState<SpinResult|null>(null);itemsRef.current=items;
 const candidates=useMemo(()=>filterActivities(randomEligibleActivities,filters),[filters]);const hasFilters=Object.keys(filters).some(key=>filters[key as keyof ActivityFilters]!==defaultFilters[key as keyof ActivityFilters]);
 useEffect(()=>{const timer=setTimeout(()=>{const saved={...defaultFilters,...readJson<Partial<ActivityFilters>>(FILTER_STORAGE_KEY,{})};const savedHistory=readJson<string[]>(RANDOM_HISTORY_KEY,[]);const next=filterActivities(randomEligibleActivities,saved);setFilters(saved);setHistory(savedHistory);setItems(next)},0);return()=>clearTimeout(timer)},[]);
 useEffect(()=>()=>cancelTimers(),[]);
 function cancelTimers(){if(redirectRef.current)clearTimeout(redirectRef.current);if(spinFallbackRef.current)clearTimeout(spinFallbackRef.current);redirectRef.current=null;spinFallbackRef.current=null}
 function clearSelection(){cancelTimers();completedRef.current=false;setSelectedResult(null);setSpinning(false);setRotation(0)}
 function update<K extends keyof ActivityFilters>(key:K,value:ActivityFilters[K]){const next={...filters,[key]:value};clearSelection();setFilters(next);localStorage.setItem(FILTER_STORAGE_KEY,JSON.stringify(next));setItems(filterActivities(randomEligibleActivities,next))}
 function resetFilters(){clearSelection();setFilters(defaultFilters);localStorage.setItem(FILTER_STORAGE_KEY,JSON.stringify(defaultFilters));setItems(randomEligibleActivities)}
 function spin(){if(spinning||selectedResult||!items.length)return;cancelTimers();completedRef.current=false;const selectedIndex=pickWheelItemIndex(items,history);if(selectedIndex<0)return;const selectedActivity=items[selectedIndex];const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;const finalRotation=getRotationForIndex(selectedIndex,items.length,reduced?1:6);const result:SpinResult={activity:selectedActivity,id:selectedActivity.id,slug:selectedActivity.slug||selectedActivity.id,title:localizeActivity(selectedActivity,language).title,index:selectedIndex,rotation:finalRotation};setSelectedResult(result);setSpinning(true);requestAnimationFrame(()=>requestAnimationFrame(()=>setRotation(finalRotation)));spinFallbackRef.current=setTimeout(()=>completeSpin(result),4000)}
 function getVisualIndex(finalRotation:number,wheelItems:Activity[]){const wheel=wheelRef.current;if(wheel){const rect=wheel.getBoundingClientRect();const hitX=rect.left+rect.width/2;const hitY=rect.top+rect.height*.08;const segment=document.elementFromPoint(hitX,hitY)?.closest<SVGPathElement>('[data-wheel-segment="true"]');const value=Number(segment?.dataset.wheelIndex);if(Number.isInteger(value)&&value>=0&&value<wheelItems.length)return value}return getIndexAtPointer(finalRotation,wheelItems.length)}
 function completeSpin(intended:SpinResult){if(completedRef.current)return;completedRef.current=true;if(spinFallbackRef.current)clearTimeout(spinFallbackRef.current);spinFallbackRef.current=null;const wheelItems=itemsRef.current;const visualIndex=getVisualIndex(intended.rotation,wheelItems);const visualActivity=wheelItems[visualIndex];if(!visualActivity)return;const result:SpinResult={activity:visualActivity,id:visualActivity.id,slug:visualActivity.slug||visualActivity.id,title:localizeActivity(visualActivity,language).title,index:visualIndex,rotation:intended.rotation};if(process.env.NODE_ENV!=="production"){console.debug("Wheel final verification",{intendedIndex:intended.index,visualIndex,intendedActivity:intended.slug,visualActivity:result.slug,finalRotation:intended.rotation});if(intended.index!==visualIndex||intended.id!==result.id)console.error("Visual wheel mismatch detected",{intendedIndex:intended.index,visualIndex,intendedActivity:intended.slug,visualActivity:result.slug,finalRotation:intended.rotation})}setSelectedResult(result);setSpinning(false);const next=nextRandomHistory(history,result.id);setHistory(next);localStorage.setItem(RANDOM_HISTORY_KEY,JSON.stringify(next));localStorage.setItem(RECENT_RANDOM_KEY,result.id);const targetSlug=result.slug;redirectRef.current=setTimeout(()=>router.push(`/activities/${targetSlug}`),800)}
 function shuffle(){clearSelection();setItems(selectWheelItems(candidates,candidates.length,Math.random,items.map(item=>item.id)))}
 const filterLabels={level:t("filter.level"),duration:t("activity.duration"),groupSize:t("filter.group"),category:t("filter.category")};const status=spinning?t("randomActivity.spinning"):selectedResult?`${selectedResult.title} ${t("randomActivity.selected")}`:t("randomActivity.description");
 return <section className="wheel-section"><div className="wheel-filter-panel"><header><div><b>{hasFilters?t("common.filter"):t("nav.activities")}</b><p>{candidates.length} {t("randomActivity.available")}</p></div>{hasFilters&&<button disabled={spinning||Boolean(selectedResult)} onClick={resetFilters}><RotateCcw/>{t("randomActivity.reset")}</button>}</header><div>{(["level","duration","groupSize","category"] as const).map(key=><label key={key}>{filterLabels[key]}<select value={filters[key]} disabled={spinning||Boolean(selectedResult)} onChange={event=>update(key,event.target.value as never)}>{activityFilterOptions[key].map(value=><option key={value}>{value}</option>)}</select></label>)}</div></div>
  <div className="wheel-status" aria-live="polite">{status}{selectedResult&&!spinning&&<small>{t("randomActivity.opening")}</small>}</div>{!candidates.length?<div className="wheel-empty"><h2>{t("randomActivity.noMatches")}</h2><button className="button button-primary" onClick={resetFilters}>{t("randomActivity.reset")}</button></div>:<><div className="wheel-wrap"><div className="wheel-pointer"/><div ref={wheelRef} className="activity-wheel" data-visible-count={items.length} onTransitionEnd={event=>{if(event.propertyName==="transform"&&selectedResult)completeSpin(selectedResult)}} style={{"--wheel-font-size":`${wheelFontSize(items.length)}px`,transform:`rotate(${rotation}deg)`,transitionDuration:spinning?"3.6s":"0s"} as React.CSSProperties}><svg viewBox="0 0 100 100" aria-hidden="true">{items.map((item,index)=><path key={item.id} d={getSegmentPath(index,items.length)} fill={colors[index%colors.length]} data-wheel-segment="true" data-wheel-index={index} data-activity-id={item.id} data-activity-slug={item.slug||item.id}/>)}</svg>{items.map((item,index)=>{const localized=localizeActivity(item,language);const lines=splitWheelTitle(localized.shortTitle);const center=getSegmentCenterAngle(index,items.length);const labelAngle=center+90;const flipped=labelAngle>90&&labelAngle<270;return <span key={item.id} className={flipped?"is-flipped":""} title={localized.title} style={{transform:`rotate(${labelAngle}deg)`}}><i>{lines.map(line=><em key={line}>{line}</em>)}</i></span>})}</div><button className="spin-button" onClick={spin} disabled={spinning||Boolean(selectedResult)}>{spinning?"…":t("randomActivity.spin")}</button></div>{candidates.length>1&&<button className="shuffle-wheel" disabled={spinning||Boolean(selectedResult)} onClick={shuffle}><Shuffle/>{t("randomActivity.shuffle")}</button>}</>}</section>}
