"use client";
import { useEffect,useMemo,useRef,useState } from "react"; import { Filter, Search, X } from "lucide-react";
import { activities } from "@/data/activities"; import { defaultFilters,filterActivities,type ActivityFilters } from "@/lib/activity-utils"; import { FILTER_STORAGE_KEY } from "@/lib/navigation"; import { ActivityCard } from "./activity-card"; import { readFavorites } from "./favorite-button";
const options={level:["All","All Level","Beginner","Intermediate","Upper-Intermediate"],duration:["All","5","10","15","20+"],groupSize:["All","2 people","3–4 people","5–8 people","9+ people"],category:["All","Ice Breaking","Speaking","Games","Discussion","Expression Practice","Picture Activities"]} as const;
export function ActivityBrowser(){const [filters,setFilters]=useState<ActivityFilters>(()=>{if(typeof window==="undefined")return defaultFilters;try{const saved=JSON.parse(localStorage.getItem(FILTER_STORAGE_KEY)||"{}");const category=new URLSearchParams(location.search).get("category");return {...defaultFilters,...saved,...(category?{category}: {})}}catch{return defaultFilters}});const [favoritesOnly,setFavoritesOnly]=useState(()=>typeof window!=="undefined"&&new URLSearchParams(location.search).get("favorites")==="true");const [drawer,setDrawer]=useState(false);const searchRef=useRef<HTMLInputElement>(null);
useEffect(()=>{if(new URLSearchParams(location.search).get("focus")==="search")setTimeout(()=>searchRef.current?.focus(),100)},[]);
useEffect(()=>{localStorage.setItem(FILTER_STORAGE_KEY,JSON.stringify(filters))},[filters]); const result=useMemo(()=>{const list=filterActivities(activities,filters);return favoritesOnly?list.filter(x=>readFavorites().includes(x.id)):list},[filters,favoritesOnly]); const active=Object.keys(filters).filter(k=>filters[k as keyof ActivityFilters]!==defaultFilters[k as keyof ActivityFilters]).length+(favoritesOnly?1:0); const set=<K extends keyof ActivityFilters>(k:K,v:ActivityFilters[K])=>setFilters(f=>({...f,[k]:v}));
return <section className="activity-browser section-shell"><div className="search-wrap"><Search/><input ref={searchRef} value={filters.search} onChange={e=>set("search",e.target.value)} placeholder="활동 검색" aria-label="활동 검색"/>{filters.search&&<button onClick={()=>set("search","")} aria-label="검색 지우기"><X/></button>}</div><button className="filter-open" onClick={()=>setDrawer(true)}><Filter/> 필터 {active>0&&<span>{active}</span>}</button><div className={drawer?"filter-drawer is-open":"filter-drawer"} aria-hidden={!drawer}><button className="filter-backdrop" onClick={()=>setDrawer(false)} aria-label="필터 닫기"/><div><header><b>활동 필터</b><button onClick={()=>setDrawer(false)} aria-label="필터 닫기"><X/></button></header><FilterGroup label="난이도" values={options.level} value={filters.level} onChange={v=>set("level",v as ActivityFilters["level"])}/><FilterGroup label="시간" values={options.duration} value={filters.duration} onChange={v=>set("duration",v as ActivityFilters["duration"])}/><FilterGroup label="인원" values={options.groupSize} value={filters.groupSize} onChange={v=>set("groupSize",v as ActivityFilters["groupSize"])}/><FilterGroup label="카테고리" values={options.category} value={filters.category} onChange={v=>set("category",v as ActivityFilters["category"])}/><button className={favoritesOnly?"chip is-active":"chip"} onClick={()=>setFavoritesOnly(v=>!v)}>♥ 즐겨찾기만</button><button className="button button-primary" onClick={()=>setDrawer(false)}>결과 {result.length}개 보기</button></div></div><div className="browser-summary"><b>{result.length}개 활동</b>{active>0&&<button onClick={()=>{setFilters(defaultFilters);setFavoritesOnly(false)}}>모두 초기화</button>}</div><div className="activity-grid">{result.map(x=><ActivityCard activity={x} key={x.id}/>)}</div></section>}
function FilterGroup({label,values,value,onChange}:{label:string;values:readonly string[];value:string;onChange:(v:string)=>void}){return <fieldset><legend>{label}</legend><div>{values.map(v=><button className={v===value?"chip is-active":"chip"} onClick={()=>onChange(v)} key={v}>{v}</button>)}</div></fieldset>}
