"use client";
import { useEffect,useMemo,useRef,useState } from "react";import { RotateCcw,Shuffle } from "lucide-react";import { useRouter } from "next/navigation";
import { randomEligibleActivities } from "@/data/activities";import { activityFilterOptions,defaultFilters,filterActivities,type ActivityFilters } from "@/lib/activity-utils";import { localizeActivity } from "@/lib/activity-localization";import { FILTER_STORAGE_KEY,RANDOM_HISTORY_KEY,RECENT_RANDOM_KEY } from "@/lib/navigation";import { nextRandomHistory,pickActivity,selectWheelItems,wheelRotation } from "@/lib/random-wheel";import type { Activity } from "@/types/activity";import { useLanguage } from "@/hooks/use-language";
const colors=["#6c4cf1","#8b6cf6","#4f63d8","#a454d2","#5579c6","#7852b9","#397f8e","#b55d78"];
const readJson=<T,>(key:string,fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key)||"") as T}catch{return fallback}};
const short=(value:string)=>value.length>13?`${value.slice(0,11)}…`:value;
export function ActivityWheel(){const {language,t}=useLanguage();const router=useRouter();const redirectRef=useRef<ReturnType<typeof setTimeout>|null>(null);const [filters,setFilters]=useState<ActivityFilters>(defaultFilters);const [items,setItems]=useState<Activity[]>(()=>randomEligibleActivities.slice(0,12));const [history,setHistory]=useState<string[]>([]);const [rotation,setRotation]=useState(0);const [spinning,setSpinning]=useState(false);const [selected,setSelected]=useState<Activity|null>(null);
 const candidates=useMemo(()=>filterActivities(randomEligibleActivities,filters),[filters]);const background=useMemo(()=>items.length?items.map((_,index)=>`${colors[index%colors.length]} ${index*360/items.length}deg ${(index+1)*360/items.length}deg`).join(","):"#eceaf4 0deg 360deg",[items]);const hasFilters=Object.keys(filters).some(key=>filters[key as keyof ActivityFilters]!==defaultFilters[key as keyof ActivityFilters]);
 useEffect(()=>{const timer=setTimeout(()=>{const saved={...defaultFilters,...readJson<Partial<ActivityFilters>>(FILTER_STORAGE_KEY,{})};const savedHistory=readJson<string[]>(RANDOM_HISTORY_KEY,[]);const next=filterActivities(randomEligibleActivities,saved);setFilters(saved);setHistory(savedHistory);setItems(selectWheelItems(next,12,Math.random,[]))},0);return()=>clearTimeout(timer)},[]);
 useEffect(()=>()=>{if(redirectRef.current)clearTimeout(redirectRef.current)},[]);
 function update<K extends keyof ActivityFilters>(key:K,value:ActivityFilters[K]){const next={...filters,[key]:value};setFilters(next);localStorage.setItem(FILTER_STORAGE_KEY,JSON.stringify(next));setItems(selectWheelItems(filterActivities(randomEligibleActivities,next),12));setSelected(null)}
 function resetFilters(){setFilters(defaultFilters);localStorage.setItem(FILTER_STORAGE_KEY,JSON.stringify(defaultFilters));setItems(selectWheelItems(randomEligibleActivities,12));setSelected(null)}
 function spin(){if(spinning||!candidates.length)return;if(candidates.length===1){finish(candidates[0]);return}const target=pickActivity(candidates,history);if(!target)return;let visual=items.filter(item=>candidates.some(candidate=>candidate.id===item.id));if(!visual.some(item=>item.id===target.id)){visual=selectWheelItems(candidates.filter(item=>item.id!==target.id),11);visual.push(target)}if(!visual.length)visual=[target];const index=visual.findIndex(item=>item.id===target.id);setItems(visual);setSelected(null);setSpinning(true);const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;requestAnimationFrame(()=>requestAnimationFrame(()=>setRotation(value=>value+wheelRotation(index,visual.length,reduced?1:6))));setTimeout(()=>finish(target),reduced?250:3600)}
 function finish(target:Activity){setSpinning(false);setSelected(target);const next=nextRandomHistory(history,target.id);setHistory(next);localStorage.setItem(RANDOM_HISTORY_KEY,JSON.stringify(next));localStorage.setItem(RECENT_RANDOM_KEY,target.id);redirectRef.current=setTimeout(()=>router.push(`/activities/${target.slug||target.id}`),1000)}
 function shuffle(){const previous=items.map(item=>item.id);setItems(selectWheelItems(candidates,12,Math.random,previous));setSelected(null)}
 const filterLabels={level:t("filter.level"),duration:t("activity.duration"),groupSize:t("filter.group"),category:t("filter.category")};const status=spinning?t("randomActivity.spinning"):selected?`${localizeActivity(selected,language).title} ${t("randomActivity.selected")}`:t("randomActivity.description");
 return <section className="wheel-section"><div className="wheel-filter-panel"><header><div><b>{hasFilters?t("common.filter"):t("nav.activities")}</b><p>{candidates.length} {t("randomActivity.available")}</p></div>{hasFilters&&<button onClick={resetFilters}><RotateCcw/>{t("randomActivity.reset")}</button>}</header><div>{(["level","duration","groupSize","category"] as const).map(key=><label key={key}>{filterLabels[key]}<select value={filters[key]} onChange={event=>update(key,event.target.value as never)}>{activityFilterOptions[key].map(value=><option key={value}>{value}</option>)}</select></label>)}</div></div>
  <div className="wheel-status" aria-live="polite">{status}{selected&&<small>{t("randomActivity.opening")}</small>}</div>{!candidates.length?<div className="wheel-empty"><h2>{t("randomActivity.noMatches")}</h2><button className="button button-primary" onClick={resetFilters}>{t("randomActivity.reset")}</button></div>:<><div className="wheel-wrap"><div className="wheel-pointer"/><div className="activity-wheel" data-visible-count={items.length} style={{background:`conic-gradient(${background})`,transform:`rotate(${rotation}deg)`,transitionDuration:spinning?"3.6s":"0s"}}>{items.map((item,index)=><span key={item.id} title={localizeActivity(item,language).title} style={{transform:`rotate(${index*360/items.length+180/items.length}deg)`}}>{short(localizeActivity(item,language).shortTitle)}</span>)}</div><button className="spin-button" onClick={spin} disabled={spinning||Boolean(selected)}>{spinning?"…":t("randomActivity.spin")}</button></div>{candidates.length>12&&<button className="shuffle-wheel" disabled={spinning||Boolean(selected)} onClick={shuffle}><Shuffle/>{t("randomActivity.shuffle")}</button>}</>}</section>}
