"use client";
import { ChevronRight, Clock3, Lightbulb, RotateCcw, Users, X } from "lucide-react";
import { useEffect,useState } from "react";
import type { ConversationContent } from "@/types/conversation-content";
import { markContent,CONTENT_KEYS } from "@/lib/conversation-content-storage";

export function ConversationSessionMode({content,items,onNext,onClose}:{content:ConversationContent;items:ConversationContent[];onNext:(item:ConversationContent)=>void;onClose:()=>void}){
 const [duration,setDuration]=useState(300);const [seconds,setSeconds]=useState(300);const [running,setRunning]=useState(false);const [followUp,setFollowUp]=useState(0);const [expressions,setExpressions]=useState(false);const [turn,setTurn]=useState(1);
 useEffect(()=>{if(!running||seconds<=0)return;const timer=window.setInterval(()=>setSeconds(value=>value-1),1000);return()=>clearInterval(timer)},[running,seconds]);
 const display=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
 function next(){const index=items.findIndex(item=>item.id===content.id);setFollowUp(0);setExpressions(false);setTurn(1);onNext(items[(index+1)%items.length])}
 function finish(){markContent(content.id,CONTENT_KEYS.completed);onClose()}
 return <div className="conversation-session" role="dialog" aria-modal="true"><header><div><span>{content.category} · {content.level}</span><h1>{content.title}</h1></div><button onClick={finish} aria-label="활동 종료"><X/></button></header><main><section className="session-question"><small>MAIN QUESTION</small><p>{content.prompt}</p></section><section className="session-controls"><div className="session-timer"><Clock3/><b>{seconds===0?"TIME!":display}</b><div>{[300,600,900].map(value=><button className={duration===value?"is-active":""} onClick={()=>{setDuration(value);setSeconds(value);setRunning(false)}} key={value}>{value/60}분</button>)}</div><button className="button button-primary" onClick={()=>setRunning(!running)}>{running?"일시정지":"타이머 시작"}</button><button onClick={()=>{setSeconds(duration);setRunning(false)}} aria-label="타이머 초기화"><RotateCcw/></button></div><div className="session-turn"><Users/><b>{turn}번째 사람 차례</b><button onClick={()=>setTurn(value=>value+1)}>다음 사람 차례 <ChevronRight/></button></div></section><section className="session-followups"><div><h2>추가 질문</h2><button disabled={followUp>=content.followUpQuestions.length} onClick={()=>setFollowUp(value=>Math.min(value+1,content.followUpQuestions.length))}>질문 하나 열기</button></div>{content.followUpQuestions.slice(0,followUp).map((question,index)=><p key={question}><span>{index+1}</span>{question}</p>)}</section><section className="session-help"><button onClick={()=>setExpressions(!expressions)}><Lightbulb/>표현 도움말 {expressions?"접기":"펼치기"}</button>{expressions&&<div>{content.usefulExpressions.map(item=><p key={item.expression}><b>{item.expression}</b>{item.meaning&&<small>{item.meaning}</small>}</p>)}</div>}</section></main><footer><button className="button button-secondary" onClick={finish}>활동 종료</button><button className="button button-primary" onClick={next}>다음 질문 <ChevronRight/></button></footer></div>
}
