"use client";
import { ChevronRight, Clock3, Lightbulb, RotateCcw, Users, X } from "lucide-react";
import { useEffect,useState } from "react";
import type { ConversationContent } from "@/types/conversation-content";
import { markContent,CONTENT_KEYS } from "@/lib/conversation-content-storage";
import { useLanguage } from "@/hooks/use-language";

export function ConversationSessionMode({content,items,onNext,onClose}:{content:ConversationContent;items:ConversationContent[];onNext:(item:ConversationContent)=>void;onClose:()=>void}){
 const {language,t}=useLanguage();
 const [duration,setDuration]=useState(300);const [seconds,setSeconds]=useState(300);const [running,setRunning]=useState(false);const [followUp,setFollowUp]=useState(0);const [expressions,setExpressions]=useState(false);const [turn,setTurn]=useState(1);
 useEffect(()=>{if(!running||seconds<=0)return;const timer=window.setInterval(()=>setSeconds(value=>value-1),1000);return()=>clearInterval(timer)},[running,seconds]);
 const display=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
 function next(){const index=items.findIndex(item=>item.id===content.id);setFollowUp(0);setExpressions(false);setTurn(1);onNext(items[(index+1)%items.length])}
 function finish(){markContent(content.id,CONTENT_KEYS.completed);onClose()}
 const words={en:{minute:"min",pause:"Pause",start:"Start timer",reset:"Reset timer",turn:"Person",open:"Reveal a question",collapse:"Hide",expand:"Show"},ko:{minute:"분",pause:"일시정지",start:"타이머 시작",reset:"타이머 초기화",turn:"번째 사람 차례",open:"질문 하나 열기",collapse:"접기",expand:"펼치기"},ja:{minute:"分",pause:"一時停止",start:"タイマー開始",reset:"タイマーをリセット",turn:"人目の番",open:"質問を開く",collapse:"閉じる",expand:"表示"},zh:{minute:"分钟",pause:"暂停",start:"开始计时",reset:"重置计时器",turn:"号发言者",open:"显示一个问题",collapse:"收起",expand:"展开"}}[language];
 return <div className="conversation-session" role="dialog" aria-modal="true"><header><div><span>{content.category} · {content.level}</span><h1>{content.title}</h1></div><button onClick={finish} aria-label={t("content.end")}><X/></button></header><main><section className="session-question"><small>{t("content.main")}</small><p>{content.prompt}</p></section><section className="session-controls"><div className="session-timer"><Clock3/><b>{seconds===0?"TIME!":display}</b><div>{[300,600,900].map(value=><button className={duration===value?"is-active":""} onClick={()=>{setDuration(value);setSeconds(value);setRunning(false)}} key={value}>{value/60}{words.minute}</button>)}</div><button className="button button-primary" onClick={()=>setRunning(!running)}>{running?words.pause:words.start}</button><button onClick={()=>{setSeconds(duration);setRunning(false)}} aria-label={words.reset}><RotateCcw/></button></div><div className="session-turn"><Users/><b>{language==="en"?`${words.turn} ${turn}`:`${turn}${words.turn}`}</b><button onClick={()=>setTurn(value=>value+1)}>{t("content.nextPerson")} <ChevronRight/></button></div></section><section className="session-followups"><div><h2>{t("content.followups")}</h2><button disabled={followUp>=content.followUpQuestions.length} onClick={()=>setFollowUp(value=>Math.min(value+1,content.followUpQuestions.length))}>{words.open}</button></div>{content.followUpQuestions.slice(0,followUp).map((question,index)=><p key={question}><span>{index+1}</span>{question}</p>)}</section><section className="session-help"><button onClick={()=>setExpressions(!expressions)}><Lightbulb/>{t("content.help")} {expressions?words.collapse:words.expand}</button>{expressions&&<div>{content.usefulExpressions.map(item=><p key={item.expression}><b>{item.expression}</b>{item.meaning&&<small>{item.meaning}</small>}</p>)}</div>}</section></main><footer><button className="button button-secondary" onClick={finish}>{t("content.end")}</button><button className="button button-primary" onClick={next}>{t("common.next")} <ChevronRight/></button></footer></div>
}
