"use client";

import { RefreshCw,X } from "lucide-react";
import { useMemo,useState } from "react";
import { getRecommendedExpressions } from "@/lib/daily-expression";
import { readRecentRecommendationIds } from "@/lib/practice-expression-storage";
import type { Expression,ExpressionLevel } from "@/types/expression";
const options:{value:ExpressionLevel|"mixed";label:string}[]=[{value:"beginner",label:"초급"},{value:"intermediate",label:"중급"},{value:"advanced",label:"상급"},{value:"mixed",label:"난이도 섞어서"}];
export function ExpressionRecommendationDialog({dateKey,onClose,onAdd}:{dateKey:string;onClose:()=>void;onAdd:(items:Expression[])=>number}){const [level,setLevel]=useState<ExpressionLevel|"mixed">("beginner");const [reroll,setReroll]=useState(0);const [selected,setSelected]=useState<string[]>([]);const [message,setMessage]=useState("");const recent=useMemo(()=>readRecentRecommendationIds(dateKey),[dateKey]);const suggestions=useMemo(()=>getRecommendedExpressions(level,dateKey,reroll,recent),[dateKey,level,recent,reroll]);function add(items:Expression[]){const count=onAdd(items);setMessage(count?`${count}개 표현을 추가했어요.`:"추가할 수 있는 자리가 없거나 이미 등록된 표현입니다.");setTimeout(()=>setMessage(""),1800);}return <div className="recommend-backdrop" role="dialog" aria-modal="true" aria-labelledby="recommend-title"><div className="recommend-dialog"><button className="recommend-close" onClick={onClose} aria-label="추천 닫기"><X/></button><span className="eyebrow">Useful expressions</span><h2 id="recommend-title">유용한 표현 5개 추천</h2><p>최근 7일 추천을 가능한 한 피하고 실제 대화에 유용한 표현을 골랐어요.</p><div className="recommend-levels">{options.map((item)=><button className={level===item.value?"is-active":""} onClick={()=>{setLevel(item.value);setReroll(0);setSelected([]);}} key={item.value}>{item.label}</button>)}</div><div className="recommend-list">{suggestions.map((item)=><label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={()=>setSelected(selected.includes(item.id)?selected.filter((id)=>id!==item.id):[...selected,item.id])}/><span><b>{item.expression}</b><small>{item.koreanMeaning}</small><em>{item.example}</em></span></label>)}</div>{message&&<p className="recommend-message" role="status">{message}</p>}<div className="recommend-actions"><button className="button button-secondary" onClick={()=>{setReroll((value)=>value+1);setSelected([]);}}><RefreshCw/>다시 추천받기</button><button className="button button-secondary" disabled={!selected.length} onClick={()=>add(suggestions.filter((item)=>selected.includes(item.id)))}>선택한 표현 추가</button><button className="button button-primary" onClick={()=>add(suggestions)}>5개 모두 추가</button></div></div></div>}
