"use client";

import Link from "next/link";
import { BookHeart, Check, ChevronDown, Copy, Plus, Search, Trash2, UserRound, X } from "lucide-react";
import { useEffect, useState } from "react";
import { activities } from "@/data/activities";
import { expressions } from "@/data/expressions";
import { useDailyContent } from "@/hooks/use-daily-content";
import { usePracticeExpressions } from "@/hooks/use-practice-expressions";
import { useStudyProfileRefresh } from "@/hooks/use-study-profile";
import { deleteSavedExpression, deleteStudyNote, getDailyProgress, getIdList, getProgressMap, getSavedExpressions, getStudyNotes, getUsageLogs, migrateLegacyNotes, saveExpression, saveStudyNote, saveUsageLog, setIdList, setProgress, STUDY_KEYS, studyId } from "@/lib/study-storage";
import { getDailyBrowserState } from "@/hooks/use-daily-content";
import { getLocalDateKey as getSeoulDateKey, shiftDateKey } from "@/lib/daily-content";
import { readPracticeDay, writePracticeDay } from "@/lib/practice-expression-storage";
import { MissionRerollButton } from "@/components/mission-reroll-button";
import { getContentById } from "@/lib/conversation-content";
import { CONTENT_KEYS,readContentProgress } from "@/lib/conversation-content-storage";
import { useLanguage } from "@/hooks/use-language";
import type { SavedExpression, SavedExpressionStatus, StudyNote, StudyStatus } from "@/types/study";
import { readSituationPractices } from "@/lib/situation-story-storage";
import { ALPHABET_PRACTICE_KEY, readAlphabetPractices } from "@/lib/alphabet-challenge-storage";
import { balanceGameItems } from "@/data/balance-game";
import { BALANCE_KEYS, readBalanceFavorites, readBalanceSessions } from "@/lib/balance-game-storage";
import { debateTopics } from "@/data/debate-pros-cons";
import { usefulExpressionPracticeItems } from "@/data/2026-07-17-useful-expression-practice";
import { readUsefulExpressionFavorites,readUsefulExpressionProgress,USEFUL_EXPRESSION_KEYS } from "@/lib/2026-07-17-useful-expression-storage";

const tabs = ["today","expressions","notes","favorites","history"] as const;
const statusLabels=(t:(key:string)=>string):Record<SavedExpressionStatus,string>=>({new:t("study.statusNew"),reviewing:t("study.statusReviewing"),used:t("study.statusUsed"),mastered:t("study.statusMastered")});

export function MyStudyView() {
  const {t}=useLanguage();const translatedTabs=[["today",t("study.today")],["expressions",t("study.expressions")],["notes",t("study.notes")],["favorites",t("study.favorites")],["history",t("study.history")]] as const;
  const [tab,setTab]=useState<(typeof tabs)[number]>(()=>{if(typeof window==="undefined")return "today";const value=new URLSearchParams(location.search).get("tab");return tabs.includes(value as (typeof tabs)[number])?value as (typeof tabs)[number]:"today"});
  const refresh=useStudyProfileRefresh();
  useEffect(()=>{const timer=setTimeout(()=>{migrateLegacyNotes();refresh()},0);return()=>clearTimeout(timer)},[refresh]);
  return <main className="my-study-page"><header className="my-study-hero"><Link href="/" className="my-study-brand">L1</Link><div><span>{t("study.profile")}</span><h1><UserRound/> {t("nav.myStudy")}</h1><p>{t("home.description")}</p></div></header><nav className="my-study-tabs" aria-label={t("nav.myStudy")}>{translatedTabs.map(([id,label])=><button key={id} className={tab===id?"is-active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav><div className="my-study-content">{tab==="today"&&<TodayTab/>}{tab==="expressions"&&<ExpressionsTab/>}{tab==="notes"&&<NotesTab/>}{tab==="favorites"&&<FavoritesTab/>}{tab==="history"&&<HistoryTab/>}</div></main>;
}

function ProgressButtons({group,id,status,memo,onUse}:{group:"missions"|"dailyExpression"|"practiceExpressions";id:string;status:StudyStatus;memo?:string;onUse?:()=>void}){
  const {t}=useLanguage();const [open,setOpen]=useState(false);const [value,setValue]=useState(memo||"");
  const update=(next:StudyStatus)=>{if(next==="used"&&onUse){onUse();return;}setProgress(group,id,next,value);};
  return <div className="study-actions"><button className={status==="completed"?"is-active":""} onClick={()=>update(status==="completed"?"not-started":"completed")}><Check/>{t("study.learned")}</button><button className={status==="used"?"is-used":""} onClick={()=>update(status==="used"?"not-started":"used")}>{t("study.used")}</button><button onClick={()=>setOpen(!open)}>{t("common.memo")}</button>{open&&<div className="inline-study-memo"><textarea value={value} onChange={(e)=>setValue(e.target.value)}/><button onClick={()=>{setProgress(group,id,status,value);setOpen(false);}}>{t("common.save")}</button></div>}</div>;
}

function UsageDialog({id,expression,group,onClose}:{id:string;expression:string;group:"dailyExpression"|"practiceExpressions";onClose:()=>void}){const {t}=useLanguage();const [situation,setSituation]=useState("");const [partner,setPartner]=useState("");const [confidence,setConfidence]=useState<1|2|3|4|5>(3);const [note,setNote]=useState("");function submit(){saveUsageLog({id:studyId(),expressionId:id,expression,date:getSeoulDateKey(),situation,partner,confidence,note,createdAt:new Date().toISOString()});setProgress(group,id,"used",note);if(group==="practiceExpressions"){const record=readPracticeDay();const next={...record,items:record.items.map(item=>item.id===id?{...item,usageCount:Math.max(1,item.usageCount),note:note||item.note}:item)};writePracticeDay(next);window.dispatchEvent(new CustomEvent("language101-practice-change",{detail:next}))}onClose();}return <div className="study-modal" role="dialog" aria-modal="true"><div><button className="modal-close" onClick={onClose} aria-label={t("common.close")}><X/></button><span className="eyebrow">REAL WORLD LOG</span><h2>{t("study.usageTitle")}</h2><b>{expression}</b><label>{t("study.situation")}<input value={situation} onChange={(e)=>setSituation(e.target.value)} placeholder={t("study.situationPlaceholder")}/></label><label>{t("study.partner")}<input value={partner} onChange={(e)=>setPartner(e.target.value)} placeholder={t("study.partnerPlaceholder")}/></label><label>{t("study.confidence")}<select value={confidence} onChange={(e)=>setConfidence(Number(e.target.value) as 1|2|3|4|5)}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><label>{t("study.freeMemo")}<textarea value={note} onChange={(e)=>setNote(e.target.value)}/></label><button className="button button-primary" onClick={submit}>{t("study.saveUsage")}</button></div></div>}

function TodayTab(){const {language,t}=useLanguage();const daily=useDailyContent();const practice=usePracticeExpressions();useStudyProfileRefresh();const progress=getDailyProgress(daily.dateKey,language);const [usage,setUsage]=useState<{id:string;expression:string;group:"dailyExpression"|"practiceExpressions"}|null>(null);const dailyLegacy=getDailyBrowserState(daily.dateKey,language);const missionDone=(id:string)=>progress.missions[id]?.status==="completed"||dailyLegacy.completedMissionIds.includes(id);const expressionAvailable=Boolean(daily.primaryExpression.expression);const expressionDone=expressionAvailable&&(progress.dailyExpression[daily.primaryExpression.id]?.status!==undefined||dailyLegacy.usedExpressionIds.includes(daily.primaryExpression.id));const completed=daily.dailyMissions.filter(m=>missionDone(m.id)).length+(expressionDone?1:0)+practice.items.filter(i=>progress.practiceExpressions[i.id]?.status&&progress.practiceExpressions[i.id].status!=="not-started"||i.usageCount>0).length;const total=daily.dailyMissions.length+(expressionAvailable?1:0)+practice.items.length;const percent=Math.round(completed/Math.max(1,total)*100);
  return <><section className="study-progress-card"><div><span>{t("study.progress")}</span><strong>{completed}/{total}</strong></div><div className="study-progress-track"><span style={{width:`${percent}%`}}/></div><p>{percent}%</p></section><StudySection title={t("mission.title")} count={`${daily.dailyMissions.filter(m=>missionDone(m.id)).length}/${daily.dailyMissions.length}`}>{daily.dailyMissions.map(m=>{const status=missionDone(m.id)?"completed":progress.missions[m.id]?.status||"not-started";return <article className="study-row" key={m.id}><div><small>{m.category}</small><b>{language==="ko"?m.textKo:m.textEn}</b></div><ProgressButtons group="missions" id={m.id} status={status} memo={progress.missions[m.id]?.memo}/></article>})}</StudySection><StudySection title={t("expression.title")} count={expressionDone?t("common.completed"):"0/1"}>{expressionAvailable?<ExpressionStudyRow id={daily.primaryExpression.id} expression={daily.primaryExpression.expression} meaning={language==="ko"?daily.primaryExpression.koreanMeaning:daily.primaryExpression.expression} group="dailyExpression" progress={progress.dailyExpression[daily.primaryExpression.id]} legacyUsed={dailyLegacy.usedExpressionIds.includes(daily.primaryExpression.id)} onUse={()=>setUsage({id:daily.primaryExpression.id,expression:daily.primaryExpression.expression,group:"dailyExpression"})}/>:null}</StudySection><StudySection title={t("practice.title")} count={`${practice.items.length}/5`}>{practice.items.map(item=><ExpressionStudyRow key={item.id} id={item.id} expression={item.expression} meaning={language==="ko"?item.koreanMeaning:item.expression} group="practiceExpressions" progress={progress.practiceExpressions[item.id]} legacyUsed={item.usageCount>0} onUse={()=>setUsage({id:item.id,expression:item.expression,group:"practiceExpressions"})}/>)}</StudySection>{usage&&<UsageDialog {...usage} onClose={()=>setUsage(null)}/>}</>;
}
function StudySection({title,count,children}:{title:string;count:string;children:React.ReactNode}){const {t}=useLanguage();const empty=!children||(Array.isArray(children)&&children.length===0);return <details className="study-section" open><summary><h2>{title}</h2><span>{count}</span><ChevronDown/></summary><div>{title===t("mission.title")&&!empty&&<MissionRerollButton compact/>}{empty?<p className="study-empty">{t("common.preparing")}</p>:children}</div></details>}
function ExpressionStudyRow({id,expression,meaning,group,progress,legacyUsed,onUse}:{id:string;expression:string;meaning:string;group:"dailyExpression"|"practiceExpressions";progress?:{status:StudyStatus;memo?:string};legacyUsed:boolean;onUse:()=>void}){const {language,t}=useLanguage();const status=progress?.status||(legacyUsed?"used":"not-started");function save(){const now=new Date().toISOString();saveExpression({id:`saved-${language}-${id}`,expression,meaning,example:"",situation:t("study.today"),language,difficulty:"",tags:[],note:"",status:"new",source:group,createdAt:now,updatedAt:now});}return <article className="study-row expression-study-row"><div><b>{expression}</b><p>{meaning}</p><small>{status==="used"?t("study.used"):status==="completed"?t("study.learned"):""}</small></div><ProgressButtons group={group} id={id} status={status} memo={progress?.memo} onUse={onUse}/><button className="save-expression-button" onClick={save}><BookHeart/>{t("expression.save")}</button></article>}

const blankSaved=():SavedExpression=>{const now=new Date().toISOString();return{id:studyId(),expression:"",meaning:"",example:"",situation:"",language:"English",difficulty:"Beginner",tags:[],note:"",status:"new",createdAt:now,updatedAt:now}};
function ExpressionsTab(){const {t}=useLanguage();useStudyProfileRefresh();const labels=statusLabels(t);const [draft,setDraft]=useState(blankSaved);const [open,setOpen]=useState(false);const [query,setQuery]=useState("");const [tag,setTag]=useState("");const [status,setStatus]=useState("");const items=getSavedExpressions();const tags=[...new Set(items.flatMap(i=>i.tags))];const filtered=items.filter(i=>(i.expression+i.meaning+i.note).toLowerCase().includes(query.toLowerCase())&&(!tag||i.tags.includes(tag))&&(!status||i.status===status));function submit(){if(!draft.expression.trim())return;saveExpression({...draft,tags:typeof draft.tags==="string"?(draft.tags as string).split(",").map(v=>v.trim()).filter(Boolean):draft.tags,updatedAt:new Date().toISOString()});setDraft(blankSaved());setOpen(false);}return <><div className="study-toolbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t("study.searchExpressions")}/></label><button className="button button-primary" onClick={()=>setOpen(!open)}><Plus/>{t("study.newExpression")}</button></div><div className="study-filters"><select value={tag} onChange={e=>setTag(e.target.value)}><option value="">{t("study.allTags")}</option>{tags.map(v=><option key={v}>{v}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">{t("study.allStatuses")}</option>{Object.entries(labels).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></div>{open&&<SavedExpressionForm value={draft} onChange={setDraft} onSave={submit}/>}<div className="saved-expression-grid">{filtered.map(item=><SavedExpressionCard key={item.id} item={item}/>)}</div>{!filtered.length&&<p className="study-empty">{t("study.noExpressions")}</p>}</>}
function SavedExpressionForm({value,onChange,onSave}:{value:SavedExpression;onChange:(v:SavedExpression)=>void;onSave:()=>void}){const {t}=useLanguage();const field=(key:keyof SavedExpression,value2:string)=>onChange({...value,[key]:value2});return <div className="study-form"><h2>{t("study.saveExpression")}</h2><label>{t("study.expressionOrWord")}<input value={value.expression} onChange={e=>field("expression",e.target.value)}/></label><label>{t("study.meaning")}<input value={value.meaning} onChange={e=>field("meaning",e.target.value)}/></label><label>{t("study.example")}<input value={value.example} onChange={e=>field("example",e.target.value)}/></label><label>{t("study.context")}<input value={value.situation} onChange={e=>field("situation",e.target.value)}/></label><label>{t("study.language")}<input value={value.language} onChange={e=>field("language",e.target.value)}/></label><label>{t("study.difficulty")}<input value={value.difficulty} onChange={e=>field("difficulty",e.target.value)}/></label><label>{t("study.tags")}<input value={value.tags.join(", ")} onChange={e=>onChange({...value,tags:e.target.value.split(",").map(v=>v.trim())})}/></label><label className="wide">{t("study.freeMemo")}<textarea value={value.note} onChange={e=>field("note",e.target.value)}/></label><button className="button button-primary" onClick={onSave}>{t("common.save")}</button></div>}
function SavedExpressionCard({item}:{item:SavedExpression}){const {t}=useLanguage();const labels=statusLabels(t);return <article className="saved-expression-card"><div><b>{item.expression}</b><p>{item.meaning}</p></div><select aria-label={t("study.status")} value={item.status} onChange={e=>saveExpression({...item,status:e.target.value as SavedExpressionStatus,updatedAt:new Date().toISOString()})}>{Object.entries(labels).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select>{item.example&&<blockquote>{item.example}</blockquote>}<small>{item.tags.join(" · ")}</small><div><button onClick={()=>navigator.clipboard.writeText(`${item.expression}\n${item.meaning}`)}><Copy/>{t("common.copy")}</button><button onClick={()=>deleteSavedExpression(item.id)}><Trash2/>{t("common.delete")}</button></div></article>}

const blankNote=():StudyNote=>{const now=new Date().toISOString();return{id:studyId(),title:"",date:getSeoulDateKey(),content:"",relatedExpressionIds:[],relatedMissionIds:[],createdAt:now,updatedAt:now}};
function NotesTab(){const {t}=useLanguage();useStudyProfileRefresh();const [query,setQuery]=useState("");const [draft,setDraft]=useState(blankNote);const [open,setOpen]=useState(false);const items=getStudyNotes().filter(n=>(n.title+n.content).toLowerCase().includes(query.toLowerCase()));function edit(note:StudyNote){setDraft(note);setOpen(true)}function submit(){if(!draft.title&&!draft.content)return;saveStudyNote({...draft,updatedAt:new Date().toISOString()});setDraft(blankNote());setOpen(false)}return <><div className="study-toolbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t("study.searchNotes")}/></label><button className="button button-primary" onClick={()=>{setDraft(blankNote());setOpen(true)}}><Plus/>{t("study.newNote")}</button></div>{open&&<div className="study-form note-form"><h2>{t("study.notes")}</h2><label>{t("study.noteTitle")}<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>{t("study.date")}<input type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label className="wide">{t("study.freeMemo")}<textarea autoFocus value={draft.content} onChange={e=>{const next={...draft,content:e.target.value,updatedAt:new Date().toISOString()};setDraft(next);if(next.title||next.content)saveStudyNote(next)}} placeholder={t("study.autoSave")}/></label><label>{t("study.relatedExpressions")}<input value={draft.relatedExpressionIds.join(", ")} onChange={e=>setDraft({...draft,relatedExpressionIds:e.target.value.split(",").map(v=>v.trim()).filter(Boolean)})}/></label><label>{t("study.relatedMissions")}<input value={draft.relatedMissionIds.join(", ")} onChange={e=>setDraft({...draft,relatedMissionIds:e.target.value.split(",").map(v=>v.trim()).filter(Boolean)})}/></label><button className="button button-primary" onClick={submit}>{t("common.complete")}</button></div>}<div className="study-note-list">{items.map(note=><article key={note.id}><div><small>{note.date}</small><b>{note.title||t("study.untitled")}</b></div><p>{note.content}</p><div><button onClick={()=>navigator.clipboard.writeText(`${note.title}\n${note.content}`)}><Copy/>{t("common.copy")}</button><button onClick={()=>edit(note)}>{t("study.edit")}</button><button onClick={()=>deleteStudyNote(note.id)}><Trash2/>{t("common.delete")}</button></div></article>)}</div>{!items.length&&<p className="study-empty">{t("study.noNotes")}</p>}</>}

function FavoritesTab(){
  const {t}=useLanguage();
  useStudyProfileRefresh();
  const activityIds=getIdList(STUDY_KEYS.favoriteActivities);const expressionIds=getIdList(STUDY_KEYS.favoriteExpressions);const practiceIds=getIdList(STUDY_KEYS.favoritePracticeExpressions);
  const topics=getIdList(CONTENT_KEYS.favorites).filter(id=>{const type=getContentById(id)?.type;return type!=="question"&&type!=="roleplay"});const questions=getIdList(CONTENT_KEYS.questions);const roleplays=getIdList(CONTENT_KEYS.roleplays);
  const remove=(key:string,id:string)=>{setIdList(key,getIdList(key).filter(v=>v!==id));if(key===CONTENT_KEYS.questions||key===CONTENT_KEYS.roleplays)setIdList(CONTENT_KEYS.favorites,getIdList(CONTENT_KEYS.favorites).filter(v=>v!==id))};
  const contentRow=(id:string,key:string)=>{const item=getContentById(id);return item&&<FavoriteRow key={id} title={item.title} subtitle={item.prompt} onRemove={()=>remove(key,id)}/>};
  const stories=readSituationPractices();
  const alphabetPractices=readAlphabetPractices();
  return <div className="favorite-groups"><FavoriteGroup title={t("study.alphabetPractice")} empty={t("study.noAlphabet")}>{alphabetPractices.map(item=><FavoriteRow key={item.id} title={`${item.winner||"Practice"} · ${item.correct} correct`} subtitle={`${item.date} · ${item.participantCount} players · ${item.level}`} href="/activities/words-game" onRemove={()=>{const next=readAlphabetPractices().filter(value=>value.id!==item.id);localStorage.setItem(ALPHABET_PRACTICE_KEY,JSON.stringify(next));window.dispatchEvent(new CustomEvent("language101-study-change"))}}/>)}</FavoriteGroup><FavoriteGroup title={t("study.storyPractice")} empty={t("study.noStories")}>{stories.map(item=><FavoriteRow key={item.id} title={item.story||item.cards.map(card=>card.value).join(" · ")} subtitle={`${item.date} · ${item.level} · confidence ${item.confidence}/5`} href="/activities/describing-picture-game" onRemove={()=>{const next=readSituationPractices().filter(value=>value.id!==item.id);localStorage.setItem("language101-sentence-story-practice",JSON.stringify(next));window.dispatchEvent(new CustomEvent("language101-study-change"))}}/>)}</FavoriteGroup><FavoriteGroup title={t("study.savedActivities")} empty={t("study.noActivities")}>{activityIds.map(id=>{const item=activities.find(a=>a.id===id);return item&&<FavoriteRow key={id} title={item.title} href={`/activities/${id}`} onRemove={()=>remove(STUDY_KEYS.favoriteActivities,id)}/>} )}</FavoriteGroup><FavoriteGroup title={t("study.savedTopics")} empty={t("study.noTopics")}>{topics.map(id=>contentRow(id,CONTENT_KEYS.favorites))}</FavoriteGroup><FavoriteGroup title={t("study.savedQuestions")} empty={t("study.noQuestions")}>{questions.map(id=>contentRow(id,CONTENT_KEYS.questions))}</FavoriteGroup><FavoriteGroup title={t("study.savedRoleplays")} empty={t("study.noRoleplays")}>{roleplays.map(id=>contentRow(id,CONTENT_KEYS.roleplays))}</FavoriteGroup><FavoriteGroup title={t("study.savedExpressions")} empty={t("study.noExpressions")}>{expressionIds.map(id=>{const item=expressions.find(e=>e.id===id);return item&&<FavoriteRow key={id} title={item.expression} subtitle={item.koreanMeaning} onRemove={()=>remove(STUDY_KEYS.favoriteExpressions,id)}/>} )}</FavoriteGroup><FavoriteGroup title={t("study.savedPractice")} empty={t("study.noUsefulFavorites")}>{practiceIds.map(id=><FavoriteRow key={id} title={id} onRemove={()=>remove(STUDY_KEYS.favoritePracticeExpressions,id)}/>)}</FavoriteGroup></div>
}
function BalanceStudyGroups(){const {t}=useLanguage();const favorites=readBalanceFavorites(),sessions=readBalanceSessions();return <><FavoriteGroup title={t("study.balanceFavorites")} empty={t("study.noBalanceFavorites")}>{favorites.map(id=>{const item=balanceGameItems.find(value=>value.id===id);return item&&<FavoriteRow key={id} title={`${item.optionA} OR ${item.optionB}`} subtitle={`${item.level} · ${item.category}`} href="/activities/balance-game/practice" onRemove={()=>{localStorage.setItem(BALANCE_KEYS.favorites,JSON.stringify(readBalanceFavorites().filter(value=>value!==id)));window.dispatchEvent(new CustomEvent("language101-study-change"))}}/>})}</FavoriteGroup><FavoriteGroup title={t("study.balanceHistory")} empty={t("study.noBalanceHistory")}>{sessions.map(item=><FavoriteRow key={item.id} title={`${item.viewed} questions · A ${item.choiceA} / B ${item.choiceB}`} subtitle={`${item.date} · ${item.mode}`} href="/activities/balance-game/practice" onRemove={()=>{localStorage.setItem(BALANCE_KEYS.sessions,JSON.stringify(readBalanceSessions().filter(value=>value.id!==item.id)));window.dispatchEvent(new CustomEvent("language101-study-change"))}}/>)}</FavoriteGroup></>}
function DebateStudyGroups(){const {t}=useLanguage();const favorites:string[]=JSON.parse(localStorage.getItem("language101-debate-favorites")||"[]"),sessions:{id:string;date:string;topic:{question:{en:string};category:string};mode:string}[]=JSON.parse(localStorage.getItem("language101-debate-sessions")||"[]");return <><FavoriteGroup title={t("study.debateFavorites")} empty={t("study.noDebateFavorites")}>{favorites.map(id=>{const item=debateTopics.find(value=>value.id===id);return item&&<FavoriteRow key={id} title={item.question.en} subtitle={`${item.category} · ${item.difficulty}`} href="/activities/debate-pros-cons/practice" onRemove={()=>{localStorage.setItem("language101-debate-favorites",JSON.stringify(favorites.filter(value=>value!==id)));window.dispatchEvent(new CustomEvent("language101-study-change"))}}/>})}</FavoriteGroup><FavoriteGroup title={t("study.debateHistory")} empty={t("study.noDebateHistory")}>{sessions.map(item=><FavoriteRow key={item.id} title={item.topic.question.en} subtitle={`${item.date} · ${item.topic.category} · ${item.mode}`} href="/activities/debate-pros-cons/practice" onRemove={()=>{localStorage.setItem("language101-debate-sessions",JSON.stringify(sessions.filter(value=>value.id!==item.id)));window.dispatchEvent(new CustomEvent("language101-study-change"))}}/>)}</FavoriteGroup></>}
function UsefulExpressionStudyGroups(){const {t}=useLanguage();const favorites=readUsefulExpressionFavorites(),progress=Object.values(readUsefulExpressionProgress()).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));return <><FavoriteGroup title={t("study.usefulFavorites")} empty={t("study.noUsefulFavorites")}>{favorites.map(id=>{const item=usefulExpressionPracticeItems.find(value=>value.id===id);return item&&<FavoriteRow key={id} title={item.expression} subtitle={`${item.koreanMeaning} · ${item.frequency}`} href="/activities/useful-expressions/practice" onRemove={()=>{localStorage.setItem(USEFUL_EXPRESSION_KEYS.favorites,JSON.stringify(favorites.filter(value=>value!==id)));window.dispatchEvent(new CustomEvent("language101-study-change"))}}/>})}</FavoriteGroup><FavoriteGroup title={t("study.usefulHistory")} empty={t("study.noUsefulHistory")}>{progress.slice(0,30).map(item=><FavoriteRow key={item.id} title={item.expression} subtitle={`${item.studyDate} · Answer ${item.answerRevealed?"✓":"–"} · Questions ${item.questionsViewed?"✓":"–"}`} href="/activities/useful-expressions/practice" onRemove={()=>{const records=readUsefulExpressionProgress();delete records[item.id];localStorage.setItem(USEFUL_EXPRESSION_KEYS.progress,JSON.stringify(records));window.dispatchEvent(new CustomEvent("language101-study-change"))}}/>)}</FavoriteGroup></>}
function FavoriteGroup({title,empty,children}:{title:string;empty:string;children:React.ReactNode}){const {t}=useLanguage();const list=Array.isArray(children)?children.filter(Boolean):children;const group=<details className="study-section" open><summary><h2>{title}</h2><ChevronDown/></summary><div>{Array.isArray(list)&&!list.length?<p className="study-empty">{empty}</p>:list}</div></details>;return title===t("study.alphabetPractice")?<><UsefulExpressionStudyGroups/><DebateStudyGroups/><BalanceStudyGroups/>{group}</>:group}
function FavoriteRow({title,subtitle,href,onRemove}:{title:string;subtitle?:string;href?:string;onRemove:()=>void}){const {t}=useLanguage();const content=<><div><b>{title}</b>{subtitle&&<p>{subtitle}</p>}</div></>;return <article className="favorite-row">{href?<Link href={href}>{content}</Link>:content}<button onClick={onRemove}><Trash2/>{t("study.remove")}</button></article>}

function HistoryTab(){const {t}=useLanguage();useStudyProfileRefresh();const today=getSeoulDateKey();const all=getProgressMap();const logs=getUsageLogs();const saved=getSavedExpressions();const completedConversations=Object.values(readContentProgress(CONTENT_KEYS.completed)).flat().length;const activeDates=new Set([...Object.keys(all).filter(d=>Object.values(all[d].missions).some(v=>v.status!=="not-started")||Object.values(all[d].dailyExpression).some(v=>v.status!=="not-started")||Object.values(all[d].practiceExpressions).some(v=>v.status!=="not-started")),...logs.map(l=>l.date),...getStudyNotes().map(n=>n.date)]);let streak=0;while(activeDates.has(shiftDateKey(today,-streak)))streak++;const week=Array.from({length:7},(_,i)=>shiftDateKey(today,-i)).filter(d=>activeDates.has(d)).length;const entries=Object.entries(all).sort(([a],[b])=>b.localeCompare(a));const count=(p:ReturnType<typeof getDailyProgress>)=>[...Object.values(p.missions),...Object.values(p.dailyExpression),...Object.values(p.practiceExpressions)].filter(v=>v.status!=="not-started").length;const todayP=getDailyProgress(today);const stats=[[t("study.todayCompleted"),count(todayP)],[t("study.weekDays"),week],[t("study.streak"),streak],[t("study.completedMissions"),Object.values(all).flatMap(p=>Object.values(p.missions)).filter(v=>v.status!=="not-started").length],[t("study.learnedExpressions"),Object.values(all).flatMap(p=>[...Object.values(p.dailyExpression),...Object.values(p.practiceExpressions)]).filter(v=>v.status==="completed").length],[t("study.usedExpressions"),logs.length],[t("study.savedExpressionCount"),saved.length],[t("study.completedTopics"),completedConversations]];return <><div className="study-stats">{stats.map(([label,value])=><article key={label}><strong>{value}</strong><span>{label}</span></article>)}</div><section className="recent-study"><h2>{t("study.recent")}</h2>{entries.length?entries.slice(0,14).map(([date,p])=><article key={date}><b>{date}</b><span>{count(p)} {t("study.completedCount")}</span></article>):<p className="study-empty">{t("study.firstHistory")}</p>}</section></>}
