"use client";

import Link from "next/link";
import { BookHeart, Check, ChevronDown, Copy, Plus, Search, Trash2, UserRound, X } from "lucide-react";
import { useEffect, useState } from "react";
import { activities } from "@/data/activities";
import { expressions } from "@/data/expressions";
import { useDailyContent } from "@/hooks/use-daily-content";
import { usePracticeExpressions } from "@/hooks/use-practice-expressions";
import { useStudyProfileRefresh } from "@/hooks/use-study-profile";
import { deleteSavedExpression, deleteStudyNote, getDailyProgress, getIdList, getProgressMap, getSavedExpressions, getStudyNotes, getUsageLogs, migrateLegacyNotes, saveExpression, saveStudyNote, saveUsageLog, setIdList, setProgress, STUDY_KEYS, studyId } from "@/lib/study-storage";
import { getDailyBrowserState } from "@/hooks/use-daily-content";
import { getLocalDateKey as getSeoulDateKey, shiftDateKey } from "@/lib/daily-content";
import { readPracticeDay, writePracticeDay } from "@/lib/practice-expression-storage";
import { MissionRerollButton } from "@/components/mission-reroll-button";
import type { SavedExpression, SavedExpressionStatus, StudyNote, StudyStatus } from "@/types/study";

const tabs = [["today","오늘"],["expressions","내 표현"],["notes","학습메모"],["favorites","즐겨찾기"],["history","학습기록"]] as const;
const statusLabel:Record<StudyStatus,string>={"not-started":"아직 안 함",completed:"학습 완료",used:"실전에서 사용"};
const savedStatusLabel:Record<SavedExpressionStatus,string>={new:"새로 배움",reviewing:"복습 중",used:"실전 사용 완료",mastered:"완전히 익힘"};

export function MyStudyView() {
  const [tab,setTab]=useState<(typeof tabs)[number][0]>(()=>{if(typeof window==="undefined")return "today";const value=new URLSearchParams(location.search).get("tab");return tabs.some(([id])=>id===value)?value as (typeof tabs)[number][0]:"today"});
  const refresh=useStudyProfileRefresh();
  useEffect(()=>{const timer=setTimeout(()=>{migrateLegacyNotes();refresh()},0);return()=>clearTimeout(timer)},[refresh]);
  return <main className="my-study-page"><header className="my-study-hero"><Link href="/" className="my-study-brand">L1</Link><div><span>PERSONAL LEARNING PROFILE</span><h1><UserRound/> My Study</h1><p>오늘의 학습부터 실제 사용 기록까지 한곳에서 관리하세요.</p></div></header><nav className="my-study-tabs" aria-label="My Study 메뉴">{tabs.map(([id,label])=><button key={id} className={tab===id?"is-active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav><div className="my-study-content">{tab==="today"&&<TodayTab/>}{tab==="expressions"&&<ExpressionsTab/>}{tab==="notes"&&<NotesTab/>}{tab==="favorites"&&<FavoritesTab/>}{tab==="history"&&<HistoryTab/>}</div></main>;
}

function ProgressButtons({group,id,status,memo,onUse}:{group:"missions"|"dailyExpression"|"practiceExpressions";id:string;status:StudyStatus;memo?:string;onUse?:()=>void}){
  const [open,setOpen]=useState(false);const [value,setValue]=useState(memo||"");
  const update=(next:StudyStatus)=>{if(next==="used"&&onUse){onUse();return;}setProgress(group,id,next,value);};
  return <div className="study-actions"><button className={status==="completed"?"is-active":""} onClick={()=>update(status==="completed"?"not-started":"completed")}><Check/>학습 완료</button><button className={status==="used"?"is-used":""} onClick={()=>update(status==="used"?"not-started":"used")}>실전에서 사용</button><button onClick={()=>setOpen(!open)}>메모</button>{open&&<div className="inline-study-memo"><textarea value={value} onChange={(e)=>setValue(e.target.value)} placeholder="완료한 날짜, 배운 점이나 다음 목표를 기록하세요."/><button onClick={()=>{setProgress(group,id,status,value);setOpen(false);}}>저장</button></div>}</div>;
}

function UsageDialog({id,expression,group,onClose}:{id:string;expression:string;group:"dailyExpression"|"practiceExpressions";onClose:()=>void}){const [situation,setSituation]=useState("");const [partner,setPartner]=useState("");const [confidence,setConfidence]=useState<1|2|3|4|5>(3);const [note,setNote]=useState("");function submit(){saveUsageLog({id:studyId(),expressionId:id,expression,date:getSeoulDateKey(),situation,partner,confidence,note,createdAt:new Date().toISOString()});setProgress(group,id,"used",note);if(group==="practiceExpressions"){const record=readPracticeDay();const next={...record,items:record.items.map(item=>item.id===id?{...item,usageCount:Math.max(1,item.usageCount),note:note||item.note}:item)};writePracticeDay(next);window.dispatchEvent(new CustomEvent("language101-practice-change",{detail:next}))}onClose();}return <div className="study-modal" role="dialog" aria-modal="true"><div><button className="modal-close" onClick={onClose}><X/></button><span className="eyebrow">REAL WORLD LOG</span><h2>어디에서 사용했나요?</h2><b>{expression}</b><label>사용한 상황<input value={situation} onChange={(e)=>setSituation(e.target.value)} placeholder="예: 언어교환 모임"/></label><label>상대방<input value={partner} onChange={(e)=>setPartner(e.target.value)} placeholder="예: 새로 만난 친구"/></label><label>자신감 1~5<select value={confidence} onChange={(e)=>setConfidence(Number(e.target.value) as 1|2|3|4|5)}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><label>자유 메모<textarea value={note} onChange={(e)=>setNote(e.target.value)}/></label><button className="button button-primary" onClick={submit}>사용 기록 저장</button></div></div>}

function TodayTab(){const daily=useDailyContent();const practice=usePracticeExpressions();useStudyProfileRefresh();const progress=getDailyProgress(daily.dateKey);const [usage,setUsage]=useState<{id:string;expression:string;group:"dailyExpression"|"practiceExpressions"}|null>(null);const dailyLegacy=getDailyBrowserState(daily.dateKey);const missionDone=(id:string)=>progress.missions[id]?.status==="completed"||dailyLegacy.completedMissionIds.includes(id);const expressionDone=progress.dailyExpression[daily.primaryExpression.id]?.status!==undefined||dailyLegacy.usedExpressionIds.includes(daily.primaryExpression.id);const completed=daily.dailyMissions.filter(m=>missionDone(m.id)).length+(expressionDone?1:0)+practice.items.filter(i=>progress.practiceExpressions[i.id]?.status&&progress.practiceExpressions[i.id].status!=="not-started"||i.usageCount>0).length;const total=4+practice.items.length;const percent=Math.round(completed/Math.max(1,total)*100);
  return <><section className="study-progress-card"><div><span>오늘의 학습 진행률</span><strong>{completed}/{total}</strong></div><div className="study-progress-track"><span style={{width:`${percent}%`}}/></div><p>{percent}% 완료 · 작은 실전 사용도 훌륭한 학습 기록이에요.</p></section><StudySection title="오늘의 미션 3개" count={`${daily.dailyMissions.filter(m=>missionDone(m.id)).length}/3`}>{daily.dailyMissions.map(m=>{const status=missionDone(m.id)?"completed":progress.missions[m.id]?.status||"not-started";return <article className="study-row" key={m.id}><div><small>{m.category}</small><b>{m.textKo}</b><p>{m.textEn}</p></div><ProgressButtons group="missions" id={m.id} status={status} memo={progress.missions[m.id]?.memo}/></article>})}</StudySection><StudySection title="오늘의 영어표현" count={expressionDone?"완료":"0/1"}><ExpressionStudyRow id={daily.primaryExpression.id} expression={daily.primaryExpression.expression} meaning={daily.primaryExpression.koreanMeaning} group="dailyExpression" progress={progress.dailyExpression[daily.primaryExpression.id]} legacyUsed={dailyLegacy.usedExpressionIds.includes(daily.primaryExpression.id)} onUse={()=>setUsage({id:daily.primaryExpression.id,expression:daily.primaryExpression.expression,group:"dailyExpression"})}/></StudySection><StudySection title="오늘 실전에서 사용할 표현" count={`${practice.items.length}/5`}><div className="study-link-row"><Link href="/practice-expressions">표현 추가·편집하기</Link></div>{practice.items.length?practice.items.map(item=><ExpressionStudyRow key={item.id} id={item.id} expression={item.expression} meaning={item.koreanMeaning} group="practiceExpressions" progress={progress.practiceExpressions[item.id]} legacyUsed={item.usageCount>0} onUse={()=>setUsage({id:item.id,expression:item.expression,group:"practiceExpressions"})}/>):<p className="study-empty">아직 고른 표현이 없습니다. 오늘의 표현에서 최대 5개를 추가해 보세요.</p>}</StudySection>{usage&&<UsageDialog {...usage} onClose={()=>setUsage(null)}/>}</>;
}
function StudySection({title,count,children}:{title:string;count:string;children:React.ReactNode}){return <details className="study-section" open><summary><h2>{title}</h2><span>{count}</span><ChevronDown/></summary><div>{title==="오늘의 미션 3개"&&<MissionRerollButton compact/>}{children}</div></details>}
function ExpressionStudyRow({id,expression,meaning,group,progress,legacyUsed,onUse}:{id:string;expression:string;meaning:string;group:"dailyExpression"|"practiceExpressions";progress?:{status:StudyStatus;memo?:string};legacyUsed:boolean;onUse:()=>void}){const status=progress?.status||(legacyUsed?"used":"not-started");function save(){const now=new Date().toISOString();saveExpression({id:`saved-${id}`,expression,meaning,example:"",situation:"오늘의 학습",language:"영어",difficulty:"",tags:[],note:"",status:"new",source:group,createdAt:now,updatedAt:now});}return <article className="study-row expression-study-row"><div><b>{expression}</b><p>{meaning}</p><small>{statusLabel[status]}</small></div><ProgressButtons group={group} id={id} status={status} memo={progress?.memo} onUse={onUse}/><button className="save-expression-button" onClick={save}><BookHeart/>내 표현에 저장</button></article>}

const blankSaved=():SavedExpression=>{const now=new Date().toISOString();return{id:studyId(),expression:"",meaning:"",example:"",situation:"",language:"영어",difficulty:"초급",tags:[],note:"",status:"new",createdAt:now,updatedAt:now}};
function ExpressionsTab(){useStudyProfileRefresh();const [draft,setDraft]=useState(blankSaved);const [open,setOpen]=useState(false);const [query,setQuery]=useState("");const [tag,setTag]=useState("");const [status,setStatus]=useState("");const items=getSavedExpressions();const tags=[...new Set(items.flatMap(i=>i.tags))];const filtered=items.filter(i=>(i.expression+i.meaning+i.note).toLowerCase().includes(query.toLowerCase())&&(!tag||i.tags.includes(tag))&&(!status||i.status===status));function submit(){if(!draft.expression.trim())return;saveExpression({...draft,tags:typeof draft.tags==="string"?(draft.tags as string).split(",").map(v=>v.trim()).filter(Boolean):draft.tags,updatedAt:new Date().toISOString()});setDraft(blankSaved());setOpen(false);}return <><div className="study-toolbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="표현, 뜻, 메모 검색"/></label><button className="button button-primary" onClick={()=>setOpen(!open)}><Plus/>새 표현</button></div><div className="study-filters"><select value={tag} onChange={e=>setTag(e.target.value)}><option value="">모든 태그</option>{tags.map(v=><option key={v}>{v}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">모든 학습 상태</option>{Object.entries(savedStatusLabel).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></div>{open&&<SavedExpressionForm value={draft} onChange={setDraft} onSave={submit}/>}<div className="saved-expression-grid">{filtered.map(item=><SavedExpressionCard key={item.id} item={item}/>)}</div>{!filtered.length&&<p className="study-empty">저장한 표현이 없습니다.</p>}</>}
function SavedExpressionForm({value,onChange,onSave}:{value:SavedExpression;onChange:(v:SavedExpression)=>void;onSave:()=>void}){const field=(key:keyof SavedExpression,value2:string)=>onChange({...value,[key]:value2});return <div className="study-form"><h2>내 표현 저장</h2><label>표현 또는 단어<input value={value.expression} onChange={e=>field("expression",e.target.value)}/></label><label>뜻<input value={value.meaning} onChange={e=>field("meaning",e.target.value)}/></label><label>예문<input value={value.example} onChange={e=>field("example",e.target.value)}/></label><label>들었거나 사용한 상황<input value={value.situation} onChange={e=>field("situation",e.target.value)}/></label><label>학습 언어<input value={value.language} onChange={e=>field("language",e.target.value)}/></label><label>난이도<input value={value.difficulty} onChange={e=>field("difficulty",e.target.value)}/></label><label>태그 (쉼표로 구분)<input value={value.tags.join(", ")} onChange={e=>onChange({...value,tags:e.target.value.split(",").map(v=>v.trim())})}/></label><label className="wide">자유 메모<textarea value={value.note} onChange={e=>field("note",e.target.value)}/></label><button className="button button-primary" onClick={onSave}>저장</button></div>}
function SavedExpressionCard({item}:{item:SavedExpression}){return <article className="saved-expression-card"><div><b>{item.expression}</b><p>{item.meaning}</p></div><select aria-label="학습 상태" value={item.status} onChange={e=>saveExpression({...item,status:e.target.value as SavedExpressionStatus,updatedAt:new Date().toISOString()})}>{Object.entries(savedStatusLabel).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select>{item.example&&<blockquote>{item.example}</blockquote>}<small>{item.tags.join(" · ")}</small><div><button onClick={()=>navigator.clipboard.writeText(`${item.expression}\n${item.meaning}`)}><Copy/>복사</button><button onClick={()=>deleteSavedExpression(item.id)}><Trash2/>삭제</button></div></article>}

const blankNote=():StudyNote=>{const now=new Date().toISOString();return{id:studyId(),title:"",date:getSeoulDateKey(),content:"",relatedExpressionIds:[],relatedMissionIds:[],createdAt:now,updatedAt:now}};
function NotesTab(){useStudyProfileRefresh();const [query,setQuery]=useState("");const [draft,setDraft]=useState(blankNote);const [open,setOpen]=useState(false);const items=getStudyNotes().filter(n=>(n.title+n.content).toLowerCase().includes(query.toLowerCase()));function edit(note:StudyNote){setDraft(note);setOpen(true)}function submit(){if(!draft.title&&!draft.content)return;saveStudyNote({...draft,updatedAt:new Date().toISOString()});setDraft(blankNote());setOpen(false)}return <><div className="study-toolbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="학습메모 검색"/></label><button className="button button-primary" onClick={()=>{setDraft(blankNote());setOpen(true)}}><Plus/>새 메모</button></div>{open&&<div className="study-form note-form"><h2>학습메모</h2><label>제목<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>날짜<input type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label className="wide">자유 메모<textarea autoFocus value={draft.content} onChange={e=>{const next={...draft,content:e.target.value,updatedAt:new Date().toISOString()};setDraft(next);if(next.title||next.content)saveStudyNote(next)}} placeholder="입력하는 동안 자동 저장됩니다."/></label><label>관련 표현<input value={draft.relatedExpressionIds.join(", ")} onChange={e=>setDraft({...draft,relatedExpressionIds:e.target.value.split(",").map(v=>v.trim()).filter(Boolean)})}/></label><label>관련 미션<input value={draft.relatedMissionIds.join(", ")} onChange={e=>setDraft({...draft,relatedMissionIds:e.target.value.split(",").map(v=>v.trim()).filter(Boolean)})}/></label><button className="button button-primary" onClick={submit}>완료</button></div>}<div className="study-note-list">{items.map(note=><article key={note.id}><div><small>{note.date}</small><b>{note.title||"제목 없는 메모"}</b></div><p>{note.content}</p><div><button onClick={()=>navigator.clipboard.writeText(`${note.title}\n${note.content}`)}><Copy/>복사</button><button onClick={()=>edit(note)}>수정</button><button onClick={()=>deleteStudyNote(note.id)}><Trash2/>삭제</button></div></article>)}</div>{!items.length&&<p className="study-empty">작성한 메모가 없습니다.</p>}</>}

function FavoritesTab(){useStudyProfileRefresh();const activityIds=getIdList(STUDY_KEYS.favoriteActivities);const expressionIds=getIdList(STUDY_KEYS.favoriteExpressions);const practiceIds=getIdList(STUDY_KEYS.favoritePracticeExpressions);const questions=getIdList(STUDY_KEYS.favoriteQuestions);const remove=(key:string,id:string)=>setIdList(key,getIdList(key).filter(v=>v!==id));return <div className="favorite-groups"><FavoriteGroup title="저장한 활동" empty="저장한 활동이 없습니다.">{activityIds.map(id=>{const item=activities.find(a=>a.id===id);return item&&<FavoriteRow key={id} title={item.title} href={`/activities/${id}`} onRemove={()=>remove(STUDY_KEYS.favoriteActivities,id)}/>} )}</FavoriteGroup><FavoriteGroup title="저장한 질문" empty="저장한 질문이 없습니다.">{questions.map(q=><FavoriteRow key={q} title={q} onRemove={()=>remove(STUDY_KEYS.favoriteQuestions,q)}/>)}</FavoriteGroup><FavoriteGroup title="저장한 표현" empty="저장한 표현이 없습니다.">{expressionIds.map(id=>{const item=expressions.find(e=>e.id===id);return item&&<FavoriteRow key={id} title={item.expression} subtitle={item.koreanMeaning} onRemove={()=>remove(STUDY_KEYS.favoriteExpressions,id)}/>} )}</FavoriteGroup><FavoriteGroup title="저장한 실전 표현" empty="저장한 실전 표현이 없습니다.">{practiceIds.map(id=><FavoriteRow key={id} title={id} onRemove={()=>remove(STUDY_KEYS.favoritePracticeExpressions,id)}/>)}</FavoriteGroup></div>}
function FavoriteGroup({title,empty,children}:{title:string;empty:string;children:React.ReactNode}){const list=Array.isArray(children)?children.filter(Boolean):children;return <details className="study-section" open><summary><h2>{title}</h2><ChevronDown/></summary><div>{Array.isArray(list)&&!list.length?<p className="study-empty">{empty}</p>:list}</div></details>}
function FavoriteRow({title,subtitle,href,onRemove}:{title:string;subtitle?:string;href?:string;onRemove:()=>void}){const content=<><div><b>{title}</b>{subtitle&&<p>{subtitle}</p>}</div></>;return <article className="favorite-row">{href?<Link href={href}>{content}</Link>:content}<button onClick={onRemove}><Trash2/>해제</button></article>}

function HistoryTab(){useStudyProfileRefresh();const today=getSeoulDateKey();const all=getProgressMap();const logs=getUsageLogs();const saved=getSavedExpressions();const activeDates=new Set([...Object.keys(all).filter(d=>Object.values(all[d].missions).some(v=>v.status!=="not-started")||Object.values(all[d].dailyExpression).some(v=>v.status!=="not-started")||Object.values(all[d].practiceExpressions).some(v=>v.status!=="not-started")),...logs.map(l=>l.date),...getStudyNotes().map(n=>n.date)]);let streak=0;while(activeDates.has(shiftDateKey(today,-streak)))streak++;const week=Array.from({length:7},(_,i)=>shiftDateKey(today,-i)).filter(d=>activeDates.has(d)).length;const entries=Object.entries(all).sort(([a],[b])=>b.localeCompare(a));const count=(p:ReturnType<typeof getDailyProgress>)=>[...Object.values(p.missions),...Object.values(p.dailyExpression),...Object.values(p.practiceExpressions)].filter(v=>v.status!=="not-started").length;const todayP=getDailyProgress(today);const stats=[["오늘 완료 개수",count(todayP)],["이번 주 학습일",week],["연속 학습일",streak],["완료한 미션 수",Object.values(all).flatMap(p=>Object.values(p.missions)).filter(v=>v.status!=="not-started").length],["학습 완료한 표현 수",Object.values(all).flatMap(p=>[...Object.values(p.dailyExpression),...Object.values(p.practiceExpressions)]).filter(v=>v.status==="completed").length],["실제 사용한 표현 수",logs.length],["저장한 표현 수",saved.length]];return <><div className="study-stats">{stats.map(([label,value])=><article key={label}><strong>{value}</strong><span>{label}</span></article>)}</div><section className="recent-study"><h2>날짜별 최근 학습 기록</h2>{entries.length?entries.slice(0,14).map(([date,p])=><article key={date}><b>{date}</b><span>{count(p)}개 완료</span></article>):<p className="study-empty">첫 학습을 완료하면 여기에 기록됩니다.</p>}</section></>}
