"use client";

import Link from "next/link";
import { Clock3,Heart,History,Lightbulb,RotateCcw } from "lucide-react";
import { useState } from "react";
import { expressions } from "@/data/expressions";
import { getExpressionFavorites } from "@/lib/storage";
import { usePracticeExpressions } from "@/hooks/use-practice-expressions";
import { ExpressionProgress } from "./expression-progress";
import { PracticeExpressionForm } from "./practice-expression-form";
import { PracticeExpressionList } from "./practice-expression-list";
import { ExpressionRecommendationDialog } from "./expression-recommendation-dialog";
export function PracticeExpressions(){const practice=usePracticeExpressions();const [recommend,setRecommend]=useState(false);const [message,setMessage]=useState("");function importYesterday(){const count=practice.addExpressions(practice.yesterday.items.map((entry)=>({id:entry.id,expression:entry.expression,koreanMeaning:entry.koreanMeaning,example:entry.example,exampleTranslation:"",usageTip:"",similarExpressions:[],level:"beginner" as const,category:"conversation" as const})),"history");setMessage(count?`어제 표현 ${count}개를 불러왔어요.`:"불러올 표현이 없거나 목록이 가득 찼어요.");}function importFavorites(){const ids=getExpressionFavorites();const count=practice.addExpressions(expressions.filter((item)=>ids.includes(item.id)),"favorite");setMessage(count?`즐겨찾기 ${count}개를 추가했어요.`:"추가할 즐겨찾기가 없거나 목록이 가득 찼어요.");}function importLastMeetup(){const last=practice.recent[0];if(!last){setMessage("지난 모임 기록이 없어요.");return;}const count=practice.addExpressions(last.items.map((entry)=>({id:entry.id,expression:entry.expression,koreanMeaning:entry.koreanMeaning,example:entry.example,exampleTranslation:"",usageTip:"",similarExpressions:[],level:"beginner" as const,category:"conversation" as const})),"history");setMessage(count?`${last.date} 표현 ${count}개를 추가했어요.`:"목록이 가득 찼거나 중복된 표현입니다.");}return <section className="practice-section section-shell section-block" id="practice-expressions"><div className="section-heading"><div><span className="eyebrow">Use it today</span><h2>오늘 실전에서 사용할 표현 5개</h2></div><p>공부해 온 표현이나 지난 모임에서 배운 표현을 적고, 오늘 대화에서 직접 사용해 보세요.</p></div><ExpressionProgress completed={practice.completedCount} total={practice.items.length} usage={practice.totalUsageCount}/><div className="practice-toolbar"><PracticeExpressionForm onSave={practice.addManual} disabled={practice.items.length>=5}/><button className="button button-secondary" onClick={()=>setRecommend(true)}><Lightbulb/>추천받기</button><button onClick={importYesterday}><RotateCcw/>어제 사용한 표현 불러오기</button><Link href="/expression-history"><Clock3/>최근 표현 보기</Link><button onClick={importFavorites}><Heart/>즐겨찾기에서 가져오기</button><button onClick={importLastMeetup}><History/>지난 모임 표현 불러오기</button></div>{message&&<p className="practice-message" role="status">{message}</p>}{practice.items.length?<PracticeExpressionList items={practice.items} onUpdate={practice.update} onRemove={practice.remove}/>:<div className="practice-empty"><b>준비한 표현이 없나요?</b><p>원어민들이 자주 사용하는 유용한 표현 5개를 추천해 드릴게요.</p><button className="button button-primary" onClick={()=>setRecommend(true)}>유용한 표현 5개 추천받기</button></div>}{recommend&&<ExpressionRecommendationDialog dateKey={practice.dateKey} onClose={()=>setRecommend(false)} onAdd={(items)=>practice.addExpressions(items,"recommendation")}/>}</section>}
