"use client";

import { Check,ChevronDown,Copy,Minus,Plus,Pencil,Trash2 } from "lucide-react";
import { useState } from "react";
import type { PracticeExpression } from "@/types/expression";
import { expressions } from "@/data/expressions";
import { localizeEnglishExpression } from "@/lib/daily-expression";
import { useLanguage } from "@/hooks/use-language";
export function PracticeExpressionList({items,onUpdate,onRemove}:{items:PracticeExpression[];onUpdate:(id:string,patch:Partial<PracticeExpression>)=>void;onRemove:(id:string)=>void}){const {language,t}=useLanguage();const [expanded,setExpanded]=useState<string[]>([]);const [editing,setEditing]=useState<string|null>(null);return <div className="practice-list">{items.map((item,index)=>{const open=expanded.includes(item.id);const source=expressions.find(entry=>entry.expression===item.expression);const meaning=source?localizeEnglishExpression(source,language).meaning:language==="ko"?item.koreanMeaning:`English expression: ${item.expression}`;return <article className={item.usageCount>0?"practice-card is-used":"practice-card"} data-expression={item.expression} key={item.id}><div className="practice-card-row"><span className="practice-index">{item.usageCount>0?<Check/>:index+1}</span><div><b>{item.expression}</b>{meaning&&<p>{meaning}</p>}</div><div className="usage-stepper"><button onClick={()=>onUpdate(item.id,{usageCount:Math.max(0,item.usageCount-1)})} aria-label={t("practice.decrease")}><Minus/></button><strong>{item.usageCount>=3?"3+":item.usageCount}</strong><button onClick={()=>onUpdate(item.id,{usageCount:item.usageCount+1})} aria-label={t("practice.increase")}><Plus/></button></div><button className="detail-toggle" onClick={()=>setExpanded(open?expanded.filter((id)=>id!==item.id):[...expanded,item.id])}>{t("practice.details")} <ChevronDown/></button></div>{open&&<div className="practice-details">{item.example&&<p><b>{t("expression.example")}</b>{item.example}</p>}<label>{t("common.memo")}<textarea value={item.note} onChange={(e)=>onUpdate(item.id,{note:e.target.value})}/></label><div><button onClick={()=>navigator.clipboard.writeText(item.expression)}><Copy/>{t("common.copy")}</button><button onClick={()=>setEditing(editing===item.id?null:item.id)}><Pencil/>{t("practice.edit")}</button><button onClick={()=>onRemove(item.id)}><Trash2/>{t("common.delete")}</button></div>{editing===item.id&&<div className="inline-edit"><label>English<input value={item.expression} onChange={(e)=>onUpdate(item.id,{expression:e.target.value})}/></label><label>{t("expression.meaning")}<input value={item.koreanMeaning} onChange={(e)=>onUpdate(item.id,{koreanMeaning:e.target.value})}/></label><label>{t("expression.example")}<input value={item.example} onChange={(e)=>onUpdate(item.id,{example:e.target.value})}/></label></div>}</div>}</article>})}</div>}
