"use client";
import { useEffect,useMemo,useState } from "react";
import { AlertTriangle,Check,Clock3,Globe2,Heart,Lightbulb,MapPin,MessageCircle,RefreshCw,Save,Smile,UserRound,Zap } from "lucide-react";
import { situationFollowUps,type SituationLevel,type SituationWord } from "@/data/situation-sentence-game";
import { cardCountForLevel,containsCard,createSituationCards,situationCombinationId,type SituationMode } from "@/lib/situation-sentence-game";
import { readSituationFavorites,saveSituationPractice,SITUATION_DRAFT_KEY,SITUATION_SETTINGS_KEY,toggleSituationFavorite } from "@/lib/situation-story-storage";
import { useLanguage } from "@/hooks/use-language";
import { FavoriteButton } from "@/components/favorite-button";

const labels={en:{title:"Situation Sentence Game",subtitle:"Build a Story",desc:"Connect the words and build an English sentence or story.",mission:"Use every card in your sentence or story.",new:"New Words",hint:"Show Hint",example:"Show Example",spoken:"Spoken Practice",written:"Writing Mode",save:"Save Story",questions:"New Questions"},ko:{title:"상황 문장 만들기",subtitle:"Build a Story",desc:"주어진 단어를 연결해 영어 문장과 이야기를 만들어 보세요.",mission:"모든 카드를 사용해 영어 문장이나 이야기를 만드세요.",new:"새 단어",hint:"힌트 보기",example:"예시 보기",spoken:"말하기 연습",written:"쓰기 모드",save:"이야기 저장",questions:"새 질문"},zh:{title:"情境造句游戏",subtitle:"Build a Story",desc:"连接给出的词语，组成英语句子或故事。",mission:"请在英语句子或故事中使用所有卡片。",new:"新词语",hint:"显示提示",example:"显示示例",spoken:"口语练习",written:"写作模式",save:"保存故事",questions:"新问题"},ja:{title:"シチュエーション英文作り",subtitle:"Build a Story",desc:"表示された単語をつなげて英語の文や物語を作りましょう。",mission:"すべてのカードを英語の文や物語で使いましょう。",new:"新しい単語",hint:"ヒント",example:"例を見る",spoken:"会話練習",written:"作文モード",save:"物語を保存",questions:"新しい質問"}} as const;
const icon={country:Globe2,place:MapPin,situation:AlertTriangle,person:UserRound,time:Clock3,emotion:Smile,expression:MessageCircle,event:Zap};
const categoryLabel={country:"Country / City",place:"Place",situation:"Situation / Problem",person:"Person",time:"Time",emotion:"Emotion",expression:"Required Expression",event:"Unexpected Event"};
const examples={beginner:"I received the wrong order at a restaurant in Japan.",intermediate:"When I was in Japan, I received the wrong order at a restaurant. I felt confused, so I asked the waiter for help. In the end, the problem was solved.",advanced:"Build a five-sentence story with a beginning, a problem, a response, an unexpected event, and an ending."};
const hints={beginner:"I was at a [place] in [country] when...",intermediate:"When I was in... / I suddenly realized that... / So I asked... / In the end...",advanced:"Set the scene, explain the problem, use the required expression, add the unexpected event, and finish with a reflection."};
const secondsFor=(value:string)=>value==="30"?30:value==="60"?60:value==="120"?120:value==="180"?180:0;

export function SituationSentenceGame(){const {language}=useLanguage();const ui=labels[language];const [level,setLevel]=useState<SituationLevel>("beginner");const [mode,setMode]=useState<SituationMode>("one");const [round,setRound]=useState(1);const cards=useMemo(()=>createSituationCards(level,`situation-round:${round}`),[level,round]);const combination=situationCombinationId(cards);const [story,setStory]=useState("");const [spoken,setSpoken]=useState(false);const [checked,setChecked]=useState<string[]>([]);const [showHint,setShowHint]=useState(false);const [showExample,setShowExample]=useState(false);const [questionOffset,setQuestionOffset]=useState(0);const [speaker,setSpeaker]=useState(1);const [groupLines,setGroupLines]=useState<string[]>([]);const [timerChoice,setTimerChoice]=useState("60");const [remaining,setRemaining]=useState(60);const [running,setRunning]=useState(false);const [confidence,setConfidence]=useState(3);const [favorite,setFavorite]=useState(false);const [message,setMessage]=useState("");
 useEffect(()=>{const timer=setTimeout(()=>{try{const settings=JSON.parse(localStorage.getItem(SITUATION_SETTINGS_KEY)||"{}");const restoredLevel=(settings.level||"beginner") as SituationLevel;if(settings.level)setLevel(restoredLevel);if(settings.mode)setMode(settings.mode);const draft=localStorage.getItem(SITUATION_DRAFT_KEY);if(draft)setStory(draft);setFavorite(readSituationFavorites().includes(situationCombinationId(createSituationCards(restoredLevel,"situation-round:1"))))}catch{}},0);return()=>clearTimeout(timer)},[]);
 useEffect(()=>{localStorage.setItem(SITUATION_SETTINGS_KEY,JSON.stringify({level,mode}))},[level,mode]);
 useEffect(()=>{localStorage.setItem(SITUATION_DRAFT_KEY,story)},[story]);
 useEffect(()=>{if(!running||remaining<=0)return;const timer=setInterval(()=>setRemaining(value=>{if(value<=1){setRunning(false);if(navigator.vibrate)navigator.vibrate([200,100,200]);return 0}return value-1}),1000);return()=>clearInterval(timer)},[running,remaining]);
 function changeLevel(next:SituationLevel){setLevel(next);setRound(value=>value+1);setStory("");setChecked([]);setFavorite(false)}
 function newWords(){setRound(value=>value+1);setStory("");setChecked([]);setShowExample(false);setMessage("");setFavorite(false)}
 function used(card:SituationWord){return spoken?checked.includes(card.id):containsCard(story,card)}
 function toggleCard(id:string){setChecked(value=>value.includes(id)?value.filter(item=>item!==id):[...value,id])}
 function save(){const now=new Date();saveSituationPractice({id:`story-${now.getTime()}`,date:now.toLocaleDateString("en-CA"),cards,story:mode==="group"?[...groupLines,story].filter(Boolean).join("\n"):story,level,mode,confidence,favorite,createdAt:now.toISOString()});localStorage.removeItem(SITUATION_DRAFT_KEY);setMessage(language==="ko"?"My Study에 저장했어요.":"Saved to My Study.")}
 function nextSpeaker(){if(story.trim())setGroupLines(lines=>[...lines,story.trim()]);setStory("");setSpeaker(value=>value%8+1)}
 function changeTimer(value:string){setTimerChoice(value);setRemaining(secondsFor(value));setRunning(false)}
 const questions=Array.from({length:3},(_,index)=>situationFollowUps[(questionOffset+index)%situationFollowUps.length]);
 return <section className="situation-game" data-card-count={cardCountForLevel(level)}><header className="situation-game-head"><div><span>BUILD YOUR STORY</span><h1>{ui.title}</h1><b>{ui.subtitle}</b><p>{ui.desc}</p></div><FavoriteButton id="describing-picture-game" label/></header>
  <div className="situation-controls"><label>Level<select value={level} onChange={event=>changeLevel(event.target.value as SituationLevel)}><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label><label>Mode<select value={mode} onChange={event=>setMode(event.target.value as SituationMode)}><option value="one">One Sentence</option><option value="three">Three Sentences</option><option value="story">Build a Story</option><option value="group">Group Story</option></select></label><button className="button button-primary" onClick={newWords}><RefreshCw/>{ui.new}</button></div>
  <div className="situation-word-grid">{cards.map(card=>{const Icon=icon[card.category];return <button type="button" className={`situation-word-card is-${card.category} ${used(card)?"is-used":""}`} key={card.id} onClick={()=>spoken&&toggleCard(card.id)}><span><Icon/>{categoryLabel[card.category]}</span><strong>{card.value}</strong>{used(card)&&<Check className="word-check"/>}</button>})}</div>
  <div className="situation-mission"><b>{level==="beginner"?"Create one sentence.":level==="intermediate"?"Create three connected sentences.":"Create a detailed story using every card."}</b><p>{ui.mission}</p><div><button onClick={()=>setShowHint(value=>!value)}><Lightbulb/>{ui.hint}</button><button onClick={()=>setShowExample(value=>!value)}>{ui.example}</button><button onClick={()=>setSpoken(value=>!value)}>{spoken?ui.written:ui.spoken}</button></div>{showHint&&<blockquote>{hints[level]}</blockquote>}{showExample&&<blockquote>{examples[level]}</blockquote>}</div>
  {mode==="group"&&groupLines.length>0&&<ol className="group-story-lines">{groupLines.map((line,index)=><li key={`${line}-${index}`}><b>Speaker {index+1}</b>{line}</li>)}</ol>}
  {!spoken?<div className="story-editor"><label>YOUR SENTENCE OR STORY<textarea value={story} onChange={event=>setStory(event.target.value)} placeholder="Write your sentence or story here..."/></label><div><span>{story.length} characters</span><button onClick={()=>setStory("")}>Clear</button>{mode==="group"&&<button className="button button-secondary" onClick={nextSpeaker}>Next Speaker · {speaker}</button>}</div></div>:<p className="spoken-note">Tap each word card when you use it. {checked.length}/{cards.length} completed</p>}
  <div className="situation-timer"><Clock3/><strong>{String(Math.floor(remaining/60)).padStart(2,"0")}:{String(remaining%60).padStart(2,"0")}</strong><select value={timerChoice} onChange={event=>changeTimer(event.target.value)}><option value="30">30 seconds</option><option value="60">1 minute</option><option value="120">2 minutes</option><option value="180">3 minutes</option><option value="0">No timer</option></select><button onClick={()=>setRunning(value=>!value)} disabled={!secondsFor(timerChoice)}>{running?"Pause":"Start"}</button><button onClick={()=>changeTimer(timerChoice)}>Reset</button></div>
  <section className="situation-questions"><header><h2>Keep the conversation going</h2><button onClick={()=>setQuestionOffset(value=>(value+3)%situationFollowUps.length)}><RefreshCw/>{ui.questions}</button></header>{questions.map(question=><p key={question}>{question}</p>)}</section>
  <footer className="situation-save"><label>Confidence <select value={confidence} onChange={event=>setConfidence(Number(event.target.value))}>{[1,2,3,4,5].map(value=><option key={value}>{value}</option>)}</select></label><button className={favorite?"is-active":""} onClick={()=>setFavorite(toggleSituationFavorite(combination))}><Heart fill={favorite?"currentColor":"none"}/>Favorite combination</button><button className="button button-primary" onClick={save}><Save/>{ui.save}</button><button className="button button-secondary" onClick={newWords}>Finish Activity</button>{message&&<p role="status">{message}</p>}</footer>
 </section>}
