export const USEFUL_EXPRESSION_KEYS={favorites:"language101-useful-expression-favorites",progress:"language101-useful-expression-progress",recent:"language101-useful-expression-recent"} as const;
export type UsefulExpressionStudyRecord={id:string;expression:string;studyDate:string;answerRevealed:boolean;questionsViewed:boolean;favorite:boolean;updatedAt:string};
const read=<T,>(key:string,fallback:T):T=>{if(typeof window==="undefined")return fallback;try{return JSON.parse(localStorage.getItem(key)||"")as T}catch{return fallback}};
export const readUsefulExpressionFavorites=()=>read<string[]>(USEFUL_EXPRESSION_KEYS.favorites,[]);
export const readUsefulExpressionProgress=()=>read<Record<string,UsefulExpressionStudyRecord>>(USEFUL_EXPRESSION_KEYS.progress,{});
export const readUsefulExpressionRecent=()=>read<string[]>(USEFUL_EXPRESSION_KEYS.recent,[]);
const announce=()=>window.dispatchEvent(new CustomEvent("language101-study-change"));
export function updateUsefulExpressionProgress(id:string,expression:string,patch:Partial<Pick<UsefulExpressionStudyRecord,"answerRevealed"|"questionsViewed"|"favorite">>){const records=readUsefulExpressionProgress(),current=records[id];records[id]={id,expression,studyDate:current?.studyDate||new Date().toLocaleDateString("en-CA"),answerRevealed:current?.answerRevealed||false,questionsViewed:current?.questionsViewed||false,favorite:current?.favorite||false,updatedAt:new Date().toISOString(),...patch};localStorage.setItem(USEFUL_EXPRESSION_KEYS.progress,JSON.stringify(records));announce();return records[id]}
export function toggleUsefulExpressionFavorite(id:string,expression:string){const favorites=new Set(readUsefulExpressionFavorites());if(favorites.has(id))favorites.delete(id);else favorites.add(id);const favorite=favorites.has(id);localStorage.setItem(USEFUL_EXPRESSION_KEYS.favorites,JSON.stringify([...favorites]));updateUsefulExpressionProgress(id,expression,{favorite});return favorite}
export function rememberUsefulExpression(id:string){const next=[id,...readUsefulExpressionRecent().filter(value=>value!==id)].slice(0,10);localStorage.setItem(USEFUL_EXPRESSION_KEYS.recent,JSON.stringify(next));return next}
