import { dailyStorageKey, getLocalDateKey, shiftDateKey } from "@/lib/daily-content";
import { getDailyPracticeExpressions } from "@/lib/daily-expression";
import { getStoredLanguage } from "@/lib/i18n";import type { SupportedLanguage } from "@/types/language";
import type { Expression, PracticeDayRecord, PracticeExpression } from "@/types/expression";
import { addUniqueUpToFive } from "@/lib/expression-rules";

export const practiceStorageKey = (dateKey:string,language?:SupportedLanguage) => {void language;return `language101-practice-expressions-${dateKey}`};
const legacyPracticeStorageKey=(dateKey:string,language:SupportedLanguage)=>`language101-practice-expressions-${language}-${dateKey}`;
const blank = (date:string):PracticeDayRecord => ({ date,items:[],recommendationIds:[] });
export function readPracticeDay(date=getLocalDateKey(),language:SupportedLanguage=getStoredLanguage()):PracticeDayRecord { if (typeof window === "undefined") return blank(date); try { const stored=localStorage.getItem(practiceStorageKey(date))||localStorage.getItem(legacyPracticeStorageKey(date,"en"))||localStorage.getItem(legacyPracticeStorageKey(date,language));if(stored){const record={...blank(date),...JSON.parse(stored)};if(!localStorage.getItem(practiceStorageKey(date)))writePracticeDay(record);return record}const selected=getDailyPracticeExpressions(date,5);const record={date,items:selected.map(item=>({id:`daily-${item.id}`,expression:item.expression,koreanMeaning:item.koreanMeaning,example:item.example,note:"",usageCount:0,source:"recommendation" as const,createdAt:`${date}T00:00:00`})),recommendationIds:selected.map(item=>item.id)};writePracticeDay(record);return record; } catch { return blank(date); } }
export function writePracticeDay(record:PracticeDayRecord,language:SupportedLanguage=getStoredLanguage()) { localStorage.setItem(practiceStorageKey(record.date,language),JSON.stringify(record)); window.dispatchEvent(new CustomEvent("language101-study-change")); }
export function expressionToPractice(item:Expression,source:PracticeExpression["source"]="recommendation"):PracticeExpression { return { id:`${item.id}-${Date.now()}`,expression:item.expression,koreanMeaning:item.koreanMeaning,example:item.example,note:"",usageCount:0,source,createdAt:new Date().toISOString() }; }
function readStoredPracticeDay(date:string,language:SupportedLanguage):PracticeDayRecord { if(typeof window==="undefined")return blank(date);try{const value=localStorage.getItem(practiceStorageKey(date))||localStorage.getItem(legacyPracticeStorageKey(date,"en"))||localStorage.getItem(legacyPracticeStorageKey(date,language));return value?{...blank(date),...JSON.parse(value)}:blank(date)}catch{return blank(date)} }
export function readRecentPracticeDays(date=getLocalDateKey(),days=30,language:SupportedLanguage=getStoredLanguage()) { return Array.from({length:days},(_,index) => readStoredPracticeDay(shiftDateKey(date,-(index+1)),language)).filter((record) => record.items.length); }
export function readRecentRecommendationIds(date=getLocalDateKey(),days=7,language:SupportedLanguage=getStoredLanguage()) { return readRecentPracticeDays(date,days,language).flatMap((record) => record.recommendationIds); }
export function addPracticeItems(record:PracticeDayRecord,items:PracticeExpression[]) { return { ...record,items:addUniqueUpToFive(record.items,items) }; }
export function migrateLegacyDailyState(date=getLocalDateKey()) { try { const key=dailyStorageKey(date); return JSON.parse(localStorage.getItem(key)||"{}"); } catch { return {}; } }
