import type { Activity } from "@/types/activity";
export function uniqueActivities(items:Activity[]){return [...new Map(items.filter(item=>String(item.id||"").trim()&&String(item.title||item.id).trim()&&item.enabled!==false&&item.randomEligible!==false).map(item=>[item.id,item])).values()]}
export function selectWheelItems(items:Activity[],limit=12,random=Math.random,previous:string[]=[]){const unique=uniqueActivities(items);const different=unique.filter(item=>!previous.includes(item.id));const pool=different.length>=Math.min(limit,unique.length)?different:unique;return [...pool].sort(()=>random()-.5).slice(0,limit)}
export function pickWheelIndex(length:number,lastId:string|null,items:Activity[],random=Math.random){if(!length)return -1;const allowed=items.map((_,i)=>i).filter(i=>items[i]?.id!==lastId);const pool=allowed.length?allowed:items.map((_,i)=>i);return pool[Math.floor(random()*pool.length)]}
export function pickActivity(items:Activity[],history:string[],random=Math.random){const unique=uniqueActivities(items);if(!unique.length)return null;let pool=unique.filter(item=>!history.slice(0,5).includes(item.id));if(!pool.length)pool=unique.filter(item=>item.id!==history[0]);if(!pool.length)pool=unique;return pool[Math.floor(random()*pool.length)]}
export function nextRandomHistory(history:string[],id:string){return [id,...history.filter(value=>value!==id)].slice(0,5)}
export function wheelRotation(index:number,total:number,turns=6){const slice=360/total;return turns*360-(index*slice+slice/2)}
export function nextWheelRotation(current:number,index:number,total:number,turns=6){if(total<=0)return current;const slice=360/total;const target=(360-(index*slice+slice/2)+360)%360;const normalized=((current%360)+360)%360;const delta=turns*360+((target-normalized+360)%360);return current+delta}
export function selectedIndexFromRotation(rotation:number,itemCount:number,pointerOffset=0){if(itemCount<=0)return -1;const segment=360/itemCount;const normalized=((rotation%360)+360)%360;const pointerAngle=(360-normalized+pointerOffset+360)%360;return Math.floor(pointerAngle/segment)%itemCount}
export function pickWheelItemIndex(items:Activity[],history:string[],random=Math.random){if(!items.length)return -1;let indices=items.map((_,index)=>index).filter(index=>!history.slice(0,5).includes(items[index].id));if(!indices.length)indices=items.map((_,index)=>index).filter(index=>items[index].id!==history[0]);if(!indices.length)indices=items.map((_,index)=>index);return indices[Math.floor(random()*indices.length)]}
export function wheelFontSize(itemCount:number,compact=false){if(compact)return itemCount<=8?13:itemCount<=12?11:9;return itemCount<=8?16:itemCount<=12?13:10}
export function splitWheelTitle(title:string,maxCharacters=10){const words=title.trim().split(/\s+/);if(title.length<=maxCharacters)return[title];const lines=["",""];for(const word of words){const target=!lines[1]&&(!lines[0]||(`${lines[0]} ${word}`).trim().length<=maxCharacters)?0:1;lines[target]=`${lines[target]} ${word}`.trim()}return lines.filter(Boolean).slice(0,2)}
