import { expressions } from "../data/expressions"; import { missions,missionCategories } from "../data/missions"; import { duplicateValues,normalizeContent,tokenJaccard } from "../lib/content-normalization";
const errors:string[]=[];const warnings:string[]=[];
const duplicateIds=<T extends{id:string}>(items:T[])=>duplicateValues(items,item=>item.id);
for(const [label,duplicates] of [["expression id",duplicateIds(expressions)],["expression",duplicateValues(expressions,item=>item.expression)],["example",duplicateValues(expressions,item=>item.example)],["mission id",duplicateIds(missions)],["mission title",duplicateValues(missions,item=>item.title)],["mission description",duplicateValues(missions,item=>item.description)]] as const)if(duplicates.length)errors.push(`${label}: ${duplicates.length} duplicates`);
if(expressions.length<900)errors.push(`expressions: ${expressions.length}/900`);for(const level of ["beginner","intermediate","advanced"] as const){const count=expressions.filter(item=>item.level===level).length;if(count<300)errors.push(`${level}: ${count}/300`)}
if(expressions.filter(item=>item.recommendedForPractice).length<300)errors.push("practice recommendations below 300");if(missions.length<300)errors.push(`missions: ${missions.length}/300`);for(const category of missionCategories){const count=missions.filter(item=>item.category===category).length;if(count<20)errors.push(`${category}: ${count}/20`)}
for(const item of expressions){if(!item.example.includes(item.expression))errors.push(`example missing expression: ${item.id}`);if(!item.expression||!item.koreanMeaning||!item.usageTip)errors.push(`missing expression field: ${item.id}`)}
for(const item of missions)if(!item.title||!item.description||!item.textEn)errors.push(`missing mission field: ${item.id}`);
function near<T>(items:T[],select:(item:T)=>string,label:string){for(let i=0;i<items.length;i++)for(let j=i+1;j<items.length;j++){const a=select(items[i]),b=select(items[j]);if(normalizeContent(a)!==normalizeContent(b)&&tokenJaccard(a,b)>=.85)warnings.push(`${label}: ${a} <> ${b}`)}}
near(expressions,item=>item.expression,"near expression");near(missions,item=>item.title,"near mission");
console.log(JSON.stringify({expressions:expressions.length,levels:Object.fromEntries(["beginner","intermediate","advanced"].map(level=>[level,expressions.filter(item=>item.level===level).length])),recommended:expressions.filter(item=>item.recommendedForPractice).length,missions:missions.length,missionCategories:Object.fromEntries(missionCategories.map(category=>[category,missions.filter(item=>item.category===category).length])),exactDuplicates:errors.filter(value=>value.includes("duplicates")).length,nearDuplicateWarnings:warnings.length,lastValidated:new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul"}).format(new Date())},null,2));
if(warnings.length)console.warn(warnings.slice(0,20).join("\n"));if(errors.length){console.error(errors.join("\n"));process.exit(1)}
