"use client";
import { useEffect,useLayoutEffect,useRef,useState } from "react";
import { tutorialSteps } from "@/data/tutorial-steps";
import { useTutorial } from "@/hooks/use-tutorial";
import { useLanguage } from "@/hooks/use-language";

type Box={top:number;left:number;width:number;height:number};
const visible=(element:HTMLElement)=>{const style=getComputedStyle(element);const rect=element.getBoundingClientRect();return style.display!=="none"&&style.visibility!=="hidden"&&rect.width>0&&rect.height>0};
export function TutorialOverlay(){const {stepIndex,nextStep,previousStep,skipTutorial,finishTutorial}=useTutorial();const {t}=useLanguage();const dialogRef=useRef<HTMLDivElement>(null);const [box,setBox]=useState<Box|null>(null);const step=tutorialSteps[stepIndex];const last=stepIndex===tutorialSteps.length-1;
  useLayoutEffect(()=>{const update=()=>{const targets=[...document.querySelectorAll<HTMLElement>(`[data-tutorial="${step.target}"]`)];const target=targets.find(visible);if(!target){setBox(null);return}target.scrollIntoView({block:"center",behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"});const rect=target.getBoundingClientRect();setBox({top:Math.max(8,rect.top-7),left:Math.max(8,rect.left-7),width:Math.min(innerWidth-16,rect.width+14),height:rect.height+14})};update();const timer=setTimeout(update,280);addEventListener("resize",update);addEventListener("scroll",update,true);return()=>{clearTimeout(timer);removeEventListener("resize",update);removeEventListener("scroll",update,true)}},[step.target]);
  useEffect(()=>{const previous=document.body.style.overflow;document.body.style.overflow="hidden";dialogRef.current?.focus();const keyboard=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();skipTutorial();return}if(event.key!=="Tab"||!dialogRef.current)return;const focusable=[...dialogRef.current.querySelectorAll<HTMLElement>("button,[href],[tabindex]:not([tabindex='-1'])")];if(!focusable.length)return;const first=focusable[0],lastItem=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();lastItem.focus()}else if(!event.shiftKey&&document.activeElement===lastItem){event.preventDefault();first.focus()}};addEventListener("keydown",keyboard);return()=>{document.body.style.overflow=previous;removeEventListener("keydown",keyboard)}},[skipTutorial]);
  const cardStyle=box?{top:Math.max(16,Math.min(innerHeight-280,box.top+box.height+14)),left:Math.max(16,Math.min(innerWidth-360,box.left))}:undefined;
  return <div className="tutorial-layer"><div className="tutorial-shade"/>{box&&<div className="tutorial-spotlight" style={box}/>}<div ref={dialogRef} className="tutorial-dialog" style={cardStyle} role="dialog" aria-modal="true" aria-labelledby="tutorial-title" aria-describedby="tutorial-description" aria-live="polite" tabIndex={-1}><span className="tutorial-step-badge">{stepIndex+1}</span><h2 id="tutorial-title">{t(step.titleKey)}</h2><p id="tutorial-description">{t(step.descriptionKey)}</p><div className="tutorial-dots" aria-label={`${stepIndex+1} / ${tutorialSteps.length}`}>{tutorialSteps.map((item,index)=><span className={index===stepIndex?"is-active":""} key={item.id}/>)}</div><div className="tutorial-actions">{!last&&<button className="tutorial-skip" onClick={skipTutorial}>{t("tutorial.skip")}</button>}<div>{stepIndex>0&&<button className="button button-secondary" onClick={previousStep}>{t("tutorial.previous")}</button>}<button className="button button-primary" onClick={last?finishTutorial:nextStep}>{t(last?"tutorial.start":"tutorial.next")}</button></div></div></div></div>;
}
